/**
 * English Language Question Bank
 * Based on SSC CGL/CHSL/MTS, RRB NTPC, IBPS PO/Clerk PYQ patterns.
 * Covers: Synonyms, Antonyms, Sentence Correction, Idioms/Phrases,
 * One-word substitution, Spelling, Fill-in-the-blanks, Cloze,
 * Voice/Narration, Para jumbles (simplified).
 * 500+ unique items.
 */
module.exports = {
  synonyms: [
    {word:'Abandon',answer:'Forsake',options:['Forsake','Retain','Keep','Hold']},
    {word:'Abate',answer:'Reduce',options:['Reduce','Increase','Grow','Enhance']},
    {word:'Aberration',answer:'Deviation',options:['Deviation','Normalcy','Regularity','Conformity']},
    {word:'Abhor',answer:'Detest',options:['Detest','Admire','Love','Cherish']},
    {word:'Abridge',answer:'Shorten',options:['Shorten','Extend','Lengthen','Expand']},
    {word:'Acclaim',answer:'Praise',options:['Praise','Criticise','Condemn','Denounce']},
    {word:'Adamant',answer:'Stubborn',options:['Stubborn','Flexible','Yielding','Soft']},
    {word:'Affable',answer:'Friendly',options:['Friendly','Hostile','Rude','Cold']},
    {word:'Affluent',answer:'Wealthy',options:['Wealthy','Poor','Destitute','Needy']},
    {word:'Alleviate',answer:'Relieve',options:['Relieve','Worsen','Aggravate','Intensify']},
    {word:'Ambiguous',answer:'Unclear',options:['Unclear','Obvious','Clear','Definite']},
    {word:'Amiable',answer:'Friendly',options:['Friendly','Hostile','Aggressive','Unfriendly']},
    {word:'Ample',answer:'Sufficient',options:['Sufficient','Scarce','Meagre','Insufficient']},
    {word:'Ancient',answer:'Old',options:['Old','Modern','Recent','New']},
    {word:'Appease',answer:'Pacify',options:['Pacify','Aggravate','Provoke','Irritate']},
    {word:'Ardent',answer:'Passionate',options:['Passionate','Indifferent','Apathetic','Cold']},
    {word:'Astute',answer:'Shrewd',options:['Shrewd','Foolish','Naive','Dull']},
    {word:'Audacious',answer:'Bold',options:['Bold','Timid','Cowardly','Meek']},
    {word:'Augment',answer:'Increase',options:['Increase','Decrease','Reduce','Diminish']},
    {word:'Auspicious',answer:'Favourable',options:['Favourable','Unlucky','Ominous','Inauspicious']},
    {word:'Benevolent',answer:'Kind',options:['Kind','Cruel','Malevolent','Harsh']},
    {word:'Bliss',answer:'Joy',options:['Joy','Sorrow','Misery','Grief']},
    {word:'Brave',answer:'Courageous',options:['Courageous','Timid','Cowardly','Afraid']},
    {word:'Brevity',answer:'Conciseness',options:['Conciseness','Verbosity','Length','Extension']},
    {word:'Candid',answer:'Frank',options:['Frank','Secretive','Dishonest','Evasive']},
    {word:'Cease',answer:'Stop',options:['Stop','Continue','Begin','Start']},
    {word:'Colossal',answer:'Enormous',options:['Enormous','Tiny','Small','Miniature']},
    {word:'Commence',answer:'Begin',options:['Begin','End','Finish','Conclude']},
    {word:'Compassion',answer:'Sympathy',options:['Sympathy','Cruelty','Indifference','Apathy']},
    {word:'Conceal',answer:'Hide',options:['Hide','Reveal','Expose','Display']},
    {word:'Conspicuous',answer:'Noticeable',options:['Noticeable','Hidden','Invisible','Concealed']},
    {word:'Contempt',answer:'Scorn',options:['Scorn','Respect','Admiration','Reverence']},
    {word:'Cordial',answer:'Warm',options:['Warm','Hostile','Cold','Unfriendly']},
    {word:'Dearth',answer:'Scarcity',options:['Scarcity','Abundance','Surplus','Plenty']},
    {word:'Deceive',answer:'Mislead',options:['Mislead','Guide','Inform','Enlighten']},
    {word:'Delicate',answer:'Fragile',options:['Fragile','Tough','Strong','Robust']},
    {word:'Diligent',answer:'Hardworking',options:['Hardworking','Lazy','Idle','Careless']},
    {word:'Diminish',answer:'Decrease',options:['Decrease','Increase','Grow','Expand']},
    {word:'Docile',answer:'Submissive',options:['Submissive','Rebellious','Defiant','Aggressive']},
    {word:'Dwell',answer:'Reside',options:['Reside','Leave','Depart','Vacate']},
    {word:'Eccentric',answer:'Unusual',options:['Unusual','Normal','Ordinary','Common']},
    {word:'Eloquent',answer:'Fluent',options:['Fluent','Inarticulate','Stammering','Silent']},
    {word:'Eminent',answer:'Distinguished',options:['Distinguished','Unknown','Obscure','Ordinary']},
    {word:'Endure',answer:'Bear',options:['Bear','Surrender','Quit','Yield']},
    {word:'Enormous',answer:'Huge',options:['Huge','Tiny','Small','Minute']},
    {word:'Enthusiasm',answer:'Eagerness',options:['Eagerness','Apathy','Indifference','Lethargy']},
    {word:'Exquisite',answer:'Beautiful',options:['Beautiful','Ugly','Plain','Ordinary']},
    {word:'Feeble',answer:'Weak',options:['Weak','Strong','Robust','Sturdy']},
    {word:'Ferocious',answer:'Fierce',options:['Fierce','Gentle','Tame','Mild']},
    {word:'Flourish',answer:'Prosper',options:['Prosper','Decline','Wither','Fail']},
    {word:'Frigid',answer:'Cold',options:['Cold','Warm','Hot','Tropical']},
    {word:'Frugal',answer:'Thrifty',options:['Thrifty','Extravagant','Wasteful','Lavish']},
    {word:'Futile',answer:'Useless',options:['Useless','Useful','Productive','Effective']},
    {word:'Genuine',answer:'Authentic',options:['Authentic','Fake','Counterfeit','Artificial']},
    {word:'Gratitude',answer:'Thankfulness',options:['Thankfulness','Ingratitude','Resentment','Displeasure']},
    {word:'Gregarious',answer:'Sociable',options:['Sociable','Reserved','Reclusive','Solitary']},
    {word:'Hapless',answer:'Unfortunate',options:['Unfortunate','Lucky','Fortunate','Blessed']},
    {word:'Hazardous',answer:'Dangerous',options:['Dangerous','Safe','Secure','Harmless']},
    {word:'Heretic',answer:'Dissenter',options:['Dissenter','Conformist','Follower','Believer']},
    {word:'Hostile',answer:'Unfriendly',options:['Unfriendly','Friendly','Cordial','Warm']},
    {word:'Humane',answer:'Compassionate',options:['Compassionate','Cruel','Brutal','Inhuman']},
    {word:'Immense',answer:'Vast',options:['Vast','Tiny','Small','Narrow']},
    {word:'Impeccable',answer:'Flawless',options:['Flawless','Faulty','Defective','Imperfect']},
    {word:'Impetuous',answer:'Impulsive',options:['Impulsive','Cautious','Careful','Deliberate']},
    {word:'Indigenous',answer:'Native',options:['Native','Foreign','Alien','Imported']},
    {word:'Inevitable',answer:'Unavoidable',options:['Unavoidable','Avoidable','Preventable','Optional']},
    {word:'Insolent',answer:'Rude',options:['Rude','Polite','Respectful','Courteous']},
    {word:'Jovial',answer:'Cheerful',options:['Cheerful','Gloomy','Sad','Morose']},
    {word:'Keen',answer:'Eager',options:['Eager','Apathetic','Indifferent','Reluctant']},
    {word:'Lavish',answer:'Extravagant',options:['Extravagant','Frugal','Thrifty','Economical']},
    {word:'Lethargic',answer:'Sluggish',options:['Sluggish','Energetic','Active','Lively']},
    {word:'Lucid',answer:'Clear',options:['Clear','Vague','Obscure','Confusing']},
    {word:'Magnanimous',answer:'Generous',options:['Generous','Stingy','Mean','Miserly']},
    {word:'Meticulous',answer:'Careful',options:['Careful','Careless','Sloppy','Negligent']},
    {word:'Mundane',answer:'Ordinary',options:['Ordinary','Extraordinary','Unusual','Rare']},
    {word:'Novice',answer:'Beginner',options:['Beginner','Expert','Veteran','Professional']},
    {word:'Obsolete',answer:'Outdated',options:['Outdated','Modern','Current','Updated']},
    {word:'Ominous',answer:'Threatening',options:['Threatening','Auspicious','Favourable','Promising']},
    {word:'Opulent',answer:'Luxurious',options:['Luxurious','Modest','Simple','Plain']},
    {word:'Overt',answer:'Open',options:['Open','Hidden','Secret','Covert']},
    {word:'Pensive',answer:'Thoughtful',options:['Thoughtful','Carefree','Frivolous','Lighthearted']},
    {word:'Perilous',answer:'Dangerous',options:['Dangerous','Safe','Secure','Protected']},
    {word:'Placid',answer:'Calm',options:['Calm','Agitated','Restless','Turbulent']},
    {word:'Plausible',answer:'Believable',options:['Believable','Impossible','Unbelievable','Absurd']},
    {word:'Prodigal',answer:'Wasteful',options:['Wasteful','Thrifty','Economical','Frugal']},
    {word:'Profound',answer:'Deep',options:['Deep','Shallow','Superficial','Trivial']},
    {word:'Prudent',answer:'Wise',options:['Wise','Foolish','Reckless','Imprudent']},
    {word:'Quench',answer:'Satisfy',options:['Satisfy','Intensify','Ignite','Increase']},
    {word:'Reluctant',answer:'Unwilling',options:['Unwilling','Eager','Willing','Enthusiastic']},
    {word:'Replenish',answer:'Refill',options:['Refill','Empty','Drain','Deplete']},
    {word:'Resilient',answer:'Flexible',options:['Flexible','Rigid','Fragile','Brittle']},
    {word:'Serene',answer:'Peaceful',options:['Peaceful','Noisy','Chaotic','Turbulent']},
    {word:'Solitary',answer:'Alone',options:['Alone','Social','Gregarious','Accompanied']},
    {word:'Spurious',answer:'Fake',options:['Fake','Genuine','Authentic','Real']},
    {word:'Steadfast',answer:'Firm',options:['Firm','Wavering','Unsteady','Fickle']},
    {word:'Tenacious',answer:'Persistent',options:['Persistent','Yielding','Weak','Surrendering']},
    {word:'Tranquil',answer:'Peaceful',options:['Peaceful','Disturbed','Agitated','Chaotic']},
    {word:'Trivial',answer:'Insignificant',options:['Insignificant','Important','Crucial','Vital']},
    {word:'Vague',answer:'Unclear',options:['Unclear','Clear','Definite','Precise']},
    {word:'Venerate',answer:'Respect',options:['Respect','Despise','Disregard','Condemn']},
    {word:'Vivid',answer:'Bright',options:['Bright','Dull','Faded','Dim']},
    {word:'Zeal',answer:'Enthusiasm',options:['Enthusiasm','Apathy','Indifference','Lethargy']},
  ],

  antonyms: [
    {word:'Accept',answer:'Reject',options:['Reject','Receive','Welcome','Embrace']},
    {word:'Advance',answer:'Retreat',options:['Retreat','Progress','Proceed','Continue']},
    {word:'Ancient',answer:'Modern',options:['Modern','Old','Antique','Primitive']},
    {word:'Artificial',answer:'Natural',options:['Natural','Synthetic','Fake','Manufactured']},
    {word:'Attack',answer:'Defend',options:['Defend','Assault','Strike','Invade']},
    {word:'Beautiful',answer:'Ugly',options:['Ugly','Pretty','Lovely','Handsome']},
    {word:'Benevolent',answer:'Malevolent',options:['Malevolent','Kind','Generous','Charitable']},
    {word:'Bitter',answer:'Sweet',options:['Sweet','Sour','Salty','Spicy']},
    {word:'Blame',answer:'Praise',options:['Praise','Accuse','Criticise','Condemn']},
    {word:'Bless',answer:'Curse',options:['Curse','Praise','Worship','Approve']},
    {word:'Bold',answer:'Timid',options:['Timid','Brave','Daring','Fearless']},
    {word:'Bright',answer:'Dim',options:['Dim','Shiny','Radiant','Luminous']},
    {word:'Broad',answer:'Narrow',options:['Narrow','Wide','Expansive','Vast']},
    {word:'Captivity',answer:'Freedom',options:['Freedom','Prison','Bondage','Slavery']},
    {word:'Chaos',answer:'Order',options:['Order','Disorder','Confusion','Anarchy']},
    {word:'Cheap',answer:'Expensive',options:['Expensive','Affordable','Inexpensive','Economical']},
    {word:'Cowardly',answer:'Brave',options:['Brave','Afraid','Fearful','Timid']},
    {word:'Create',answer:'Destroy',options:['Destroy','Build','Make','Construct']},
    {word:'Cruel',answer:'Kind',options:['Kind','Harsh','Brutal','Savage']},
    {word:'Decline',answer:'Accept',options:['Accept','Refuse','Deny','Reject']},
    {word:'Deep',answer:'Shallow',options:['Shallow','Profound','Intense','Extreme']},
    {word:'Dense',answer:'Sparse',options:['Sparse','Thick','Crowded','Compact']},
    {word:'Despair',answer:'Hope',options:['Hope','Gloom','Sorrow','Anguish']},
    {word:'Domestic',answer:'Foreign',options:['Foreign','Local','Internal','National']},
    {word:'Dull',answer:'Bright',options:['Bright','Boring','Monotonous','Tedious']},
    {word:'Eternal',answer:'Temporary',options:['Temporary','Permanent','Everlasting','Infinite']},
    {word:'Expand',answer:'Contract',options:['Contract','Enlarge','Grow','Extend']},
    {word:'Export',answer:'Import',options:['Import','Send','Ship','Dispatch']},
    {word:'Extravagant',answer:'Frugal',options:['Frugal','Lavish','Wasteful','Generous']},
    {word:'Fertile',answer:'Barren',options:['Barren','Productive','Rich','Lush']},
    {word:'Fiction',answer:'Fact',options:['Fact','Story','Fantasy','Myth']},
    {word:'Generous',answer:'Miserly',options:['Miserly','Liberal','Charitable','Kind']},
    {word:'Giant',answer:'Dwarf',options:['Dwarf','Huge','Enormous','Massive']},
    {word:'Guilty',answer:'Innocent',options:['Innocent','Criminal','Wrong','Culpable']},
    {word:'Honest',answer:'Dishonest',options:['Dishonest','Truthful','Sincere','Frank']},
    {word:'Humble',answer:'Proud',options:['Proud','Modest','Meek','Simple']},
    {word:'Ignorant',answer:'Knowledgeable',options:['Knowledgeable','Unaware','Illiterate','Foolish']},
    {word:'Include',answer:'Exclude',options:['Exclude','Contain','Comprise','Involve']},
    {word:'Innocent',answer:'Guilty',options:['Guilty','Pure','Naive','Simple']},
    {word:'Intentional',answer:'Accidental',options:['Accidental','Deliberate','Planned','Purposeful']},
    {word:'Junior',answer:'Senior',options:['Senior','Young','Minor','Subordinate']},
    {word:'Knowledge',answer:'Ignorance',options:['Ignorance','Wisdom','Learning','Education']},
    {word:'Lenient',answer:'Strict',options:['Strict','Tolerant','Gentle','Soft']},
    {word:'Luxury',answer:'Poverty',options:['Poverty','Comfort','Wealth','Splendour']},
    {word:'Maximum',answer:'Minimum',options:['Minimum','Greatest','Most','Peak']},
    {word:'Narrow',answer:'Wide',options:['Wide','Thin','Slim','Tight']},
    {word:'Optimist',answer:'Pessimist',options:['Pessimist','Idealist','Realist','Dreamer']},
    {word:'Permanent',answer:'Temporary',options:['Temporary','Fixed','Lasting','Enduring']},
    {word:'Profit',answer:'Loss',options:['Loss','Gain','Revenue','Income']},
    {word:'Victory',answer:'Defeat',options:['Defeat','Success','Triumph','Win']},
  ],

  sentenceCorrection: [
    {incorrect:'He go to school daily.',correct:'He goes to school daily.',options:['He goes to school daily.','He going to school daily.','He gone to school daily.','He go to school daily.']},
    {incorrect:'She have a beautiful dress.',correct:'She has a beautiful dress.',options:['She has a beautiful dress.','She having a beautiful dress.','She had a beautiful dress.','She have a beautiful dress.']},
    {incorrect:'They was playing cricket.',correct:'They were playing cricket.',options:['They were playing cricket.','They is playing cricket.','They been playing cricket.','They was playing cricket.']},
    {incorrect:'I has completed my homework.',correct:'I have completed my homework.',options:['I have completed my homework.','I had completed my homework.','I having completed my homework.','I has completed my homework.']},
    {incorrect:'She don\'t know the answer.',correct:'She doesn\'t know the answer.',options:['She doesn\'t know the answer.','She not know the answer.','She do not knows the answer.','She don\'t know the answer.']},
    {incorrect:'He is more taller than his brother.',correct:'He is taller than his brother.',options:['He is taller than his brother.','He is more tall than his brother.','He is most taller than his brother.','He is more taller than his brother.']},
    {incorrect:'I and he went to the market.',correct:'He and I went to the market.',options:['He and I went to the market.','Me and he went to the market.','I and he went to the market.','Him and me went to the market.']},
    {incorrect:'The news are very shocking.',correct:'The news is very shocking.',options:['The news is very shocking.','The news were very shocking.','The newses are very shocking.','The news are very shocking.']},
    {incorrect:'Each of the boys have a pen.',correct:'Each of the boys has a pen.',options:['Each of the boys has a pen.','Each of the boys are having a pen.','Each of the boys having a pen.','Each of the boys have a pen.']},
    {incorrect:'Neither of the answers are correct.',correct:'Neither of the answers is correct.',options:['Neither of the answers is correct.','Neither of the answer are correct.','Neither of the answers were correct.','Neither of the answers are correct.']},
    {incorrect:'He told that he is busy.',correct:'He said that he was busy.',options:['He said that he was busy.','He told that he was busy.','He said that he is busy.','He told that he is busy.']},
    {incorrect:'One should do his duty.',correct:'One should do one\'s duty.',options:['One should do one\'s duty.','One should do their duty.','One should do our duty.','One should do his duty.']},
    {incorrect:'The furnitures are expensive.',correct:'The furniture is expensive.',options:['The furniture is expensive.','The furnitures is expensive.','The furniture are expensive.','The furnitures are expensive.']},
    {incorrect:'He is knowing the answer.',correct:'He knows the answer.',options:['He knows the answer.','He is know the answer.','He knowing the answer.','He is knowing the answer.']},
    {incorrect:'I am living here since 2010.',correct:'I have been living here since 2010.',options:['I have been living here since 2010.','I was living here since 2010.','I am living here from 2010.','I am living here since 2010.']},
    {incorrect:'Supposing if it rains.',correct:'Supposing it rains.',options:['Supposing it rains.','If supposing it rains.','Suppose if it rains.','Supposing if it rains.']},
    {incorrect:'He is elder than me.',correct:'He is older than me.',options:['He is older than me.','He is more elder than me.','He is elder than I.','He is elder than me.']},
    {incorrect:'The thief was hung.',correct:'The thief was hanged.',options:['The thief was hanged.','The thief was hang.','The thief is hung.','The thief was hung.']},
    {incorrect:'Hardly I had reached when it rained.',correct:'Hardly had I reached when it rained.',options:['Hardly had I reached when it rained.','Hardly I reached when it rained.','Hardly I had reached then it rained.','Hardly I had reached when it rained.']},
    {incorrect:'He availed of the opportunity.',correct:'He availed himself of the opportunity.',options:['He availed himself of the opportunity.','He availed the opportunity.','He availed of opportunity.','He availed of the opportunity.']},
  ],

  idioms: [
    {idiom:'A piece of cake',meaning:'Very easy',options:['Very easy','A dessert item','A small part','A difficult task']},
    {idiom:'Break the ice',meaning:'Initiate conversation',options:['Initiate conversation','Break something cold','Start fighting','Cause damage']},
    {idiom:'Burn the midnight oil',meaning:'Work late at night',options:['Work late at night','Waste oil','Set fire','Cook at night']},
    {idiom:'Cry over spilt milk',meaning:'Regret something that cannot be undone',options:['Regret something that cannot be undone','Clean a mess','Be careless','Cry loudly']},
    {idiom:'Hit the nail on the head',meaning:'Say something exactly right',options:['Say something exactly right','Use a hammer','Hurt someone','Miss the point']},
    {idiom:'Once in a blue moon',meaning:'Very rarely',options:['Very rarely','Every month','Always','During full moon']},
    {idiom:'Speak volumes',meaning:'Express a lot without words',options:['Express a lot without words','Speak loudly','Read many books','Shout']},
    {idiom:'Under the weather',meaning:'Feeling ill',options:['Feeling ill','During rain','Under a cloud','Protected from sun']},
    {idiom:'A blessing in disguise',meaning:'Something good that initially seemed bad',options:['Something good that initially seemed bad','A hidden gift','A religious offering','A costume']},
    {idiom:'Bite the bullet',meaning:'Face a difficult situation bravely',options:['Face a difficult situation bravely','Eat something hard','Be scared','Act foolishly']},
    {idiom:'Cost an arm and a leg',meaning:'Be very expensive',options:['Be very expensive','Cause injury','Be cheap','Buy limbs']},
    {idiom:'Let the cat out of the bag',meaning:'Reveal a secret',options:['Reveal a secret','Free a cat','Open a bag','Buy a cat']},
    {idiom:'Kill two birds with one stone',meaning:'Achieve two things with one action',options:['Achieve two things with one action','Hunt birds','Throw stones','Be violent']},
    {idiom:'Spill the beans',meaning:'Reveal secret information',options:['Reveal secret information','Cook beans','Waste food','Drop beans']},
    {idiom:'The ball is in your court',meaning:'It is your turn to act',options:['It is your turn to act','Play tennis','Throw a ball','Go to court']},
    {idiom:'Pull someone\'s leg',meaning:'Joke with someone',options:['Joke with someone','Physically pull a leg','Help someone walk','Trip someone']},
    {idiom:'Beat around the bush',meaning:'Avoid the main topic',options:['Avoid the main topic','Hit bushes','Garden work','Search for something']},
    {idiom:'Barking up the wrong tree',meaning:'Pursuing a wrong course',options:['Pursuing a wrong course','A dog barking','Climbing a tree','Being noisy']},
    {idiom:'Get cold feet',meaning:'Become nervous or afraid',options:['Become nervous or afraid','Have cold toes','Walk barefoot','Feel cold']},
    {idiom:'Through thick and thin',meaning:'In all circumstances',options:['In all circumstances','Only in good times','During diet','Through a forest']},
    {idiom:'Turn a blind eye',meaning:'Deliberately ignore',options:['Deliberately ignore','Have eye problems','Look away','Be blind']},
    {idiom:'Add fuel to the fire',meaning:'Make a bad situation worse',options:['Make a bad situation worse','Cook food','Start a campfire','Help extinguish fire']},
    {idiom:'At the eleventh hour',meaning:'At the last moment',options:['At the last moment','At 11 o\'clock','Very early','During lunch']},
    {idiom:'Back to square one',meaning:'Start over again',options:['Start over again','Play a board game','Go backwards','Return home']},
    {idiom:'By hook or by crook',meaning:'By any means necessary',options:['By any means necessary','Using fishing equipment','By stealing','By cheating only']},
    {idiom:'To cry wolf',meaning:'To raise a false alarm',options:['To raise a false alarm','To see a wolf','To be scared','To howl']},
    {idiom:'Green with envy',meaning:'Very jealous',options:['Very jealous','Feeling sick','Wearing green','Having money']},
    {idiom:'In hot water',meaning:'In trouble',options:['In trouble','Taking a bath','Boiling water','Swimming']},
    {idiom:'Keep your chin up',meaning:'Stay positive',options:['Stay positive','Look upward','Exercise','Stretch your neck']},
    {idiom:'Nip in the bud',meaning:'Stop something at an early stage',options:['Stop something at an early stage','Pick flowers','Gardening','Bite something']},
  ],

  oneWordSubstitution: [
    {description:'One who cannot be defeated',answer:'Invincible',options:['Invincible','Inevitable','Indelible','Infallible']},
    {description:'One who knows everything',answer:'Omniscient',options:['Omniscient','Omnipotent','Omnivorous','Omnipresent']},
    {description:'One who is present everywhere',answer:'Omnipresent',options:['Omnipresent','Omniscient','Omnipotent','Omnivorous']},
    {description:'One who eats both plants and animals',answer:'Omnivorous',options:['Omnivorous','Herbivorous','Carnivorous','Insectivorous']},
    {description:'A person who lives alone',answer:'Recluse',options:['Recluse','Refugee','Recruit','Relative']},
    {description:'Fear of heights',answer:'Acrophobia',options:['Acrophobia','Claustrophobia','Hydrophobia','Agoraphobia']},
    {description:'Fear of water',answer:'Hydrophobia',options:['Hydrophobia','Acrophobia','Xenophobia','Pyrophobia']},
    {description:'Fear of enclosed spaces',answer:'Claustrophobia',options:['Claustrophobia','Acrophobia','Hydrophobia','Agoraphobia']},
    {description:'Government by the people',answer:'Democracy',options:['Democracy','Autocracy','Monarchy','Oligarchy']},
    {description:'Government by a king or queen',answer:'Monarchy',options:['Monarchy','Democracy','Anarchy','Plutocracy']},
    {description:'Rule by the wealthy',answer:'Plutocracy',options:['Plutocracy','Democracy','Theocracy','Aristocracy']},
    {description:'Absence of government',answer:'Anarchy',options:['Anarchy','Democracy','Monarchy','Theocracy']},
    {description:'A person who speaks many languages',answer:'Polyglot',options:['Polyglot','Linguist','Bilingual','Translator']},
    {description:'A person who hates mankind',answer:'Misanthrope',options:['Misanthrope','Philanthropist','Misogynist','Atheist']},
    {description:'A person who loves mankind',answer:'Philanthropist',options:['Philanthropist','Misanthrope','Optimist','Altruist']},
    {description:'Killing of oneself',answer:'Suicide',options:['Suicide','Homicide','Genocide','Fratricide']},
    {description:'Killing of a king',answer:'Regicide',options:['Regicide','Fratricide','Homicide','Patricide']},
    {description:'One who does not believe in God',answer:'Atheist',options:['Atheist','Theist','Agnostic','Fanatic']},
    {description:'A person who walks in sleep',answer:'Somnambulist',options:['Somnambulist','Insomniac','Somniloquist','Lunatic']},
    {description:'Something that cannot be erased',answer:'Indelible',options:['Indelible','Illegible','Incredible','Inedible']},
    {description:'A handwritten document',answer:'Manuscript',options:['Manuscript','Script','Transcript','Inscription']},
    {description:'A person who betrays his country',answer:'Traitor',options:['Traitor','Patriot','Rebel','Anarchist']},
    {description:'An animal that lives in water',answer:'Aquatic',options:['Aquatic','Terrestrial','Amphibian','Arboreal']},
    {description:'A place where dead bodies are kept',answer:'Mortuary',options:['Mortuary','Cemetery','Crematorium','Graveyard']},
    {description:'One who is indifferent to pleasure or pain',answer:'Stoic',options:['Stoic','Sadist','Hedonist','Masochist']},
  ],

  fillBlanks: [
    {q:'The sun _____ in the east.',answer:'rises',options:['rises','sets','falls','drops']},
    {q:'She has been working here _____ 2015.',answer:'since',options:['since','for','from','by']},
    {q:'He is _____ honest man.',answer:'an',options:['an','a','the','no article']},
    {q:'I _____ to the market yesterday.',answer:'went',options:['went','go','gone','going']},
    {q:'Neither Ram _____ Shyam was present.',answer:'nor',options:['nor','or','and','but']},
    {q:'He is senior _____ me by five years.',answer:'to',options:['to','than','from','of']},
    {q:'The train arrived _____ time.',answer:'on',options:['on','in','at','by']},
    {q:'She is the _____ girl in the class.',answer:'tallest',options:['tallest','taller','tall','more tall']},
    {q:'He insisted _____ going alone.',answer:'on',options:['on','in','for','to']},
    {q:'We should abstain _____ smoking.',answer:'from',options:['from','of','in','by']},
    {q:'He is addicted _____ drugs.',answer:'to',options:['to','by','of','with']},
    {q:'The book is _____ the table.',answer:'on',options:['on','in','at','by']},
    {q:'She _____ her homework before dinner.',answer:'finished',options:['finished','finish','finishes','finishing']},
    {q:'If I _____ you, I would study harder.',answer:'were',options:['were','was','am','be']},
    {q:'He has been waiting _____ two hours.',answer:'for',options:['for','since','from','by']},
    {q:'The teacher _____ the students to be quiet.',answer:'asked',options:['asked','told to','said to','requested']},
    {q:'_____ of the two boys is intelligent.',answer:'Neither',options:['Neither','None','No one','Nothing']},
    {q:'Every student _____ present in the class.',answer:'was',options:['was','were','are','have been']},
    {q:'She is fond _____ music.',answer:'of',options:['of','in','with','at']},
    {q:'He congratulated me _____ my success.',answer:'on',options:['on','for','at','by']},
  ],

  spelling: [
    {incorrect:'Accomodation',correct:'Accommodation',options:['Accommodation','Accomodation','Acommodation','Acomodation']},
    {incorrect:'Occassion',correct:'Occasion',options:['Occasion','Occassion','Ocassion','Ocasion']},
    {incorrect:'Recieve',correct:'Receive',options:['Receive','Recieve','Receve','Recive']},
    {incorrect:'Seperate',correct:'Separate',options:['Separate','Seperate','Seprate','Saparate']},
    {incorrect:'Definately',correct:'Definitely',options:['Definitely','Definately','Definitly','Definetely']},
    {incorrect:'Occurence',correct:'Occurrence',options:['Occurrence','Occurence','Occurrance','Ocurrence']},
    {incorrect:'Neccessary',correct:'Necessary',options:['Necessary','Neccessary','Necesary','Neccesary']},
    {incorrect:'Embarrasment',correct:'Embarrassment',options:['Embarrassment','Embarrasment','Embarassment','Embarrassement']},
    {incorrect:'Pronounciation',correct:'Pronunciation',options:['Pronunciation','Pronounciation','Pronunciaton','Prononciation']},
    {incorrect:'Independance',correct:'Independence',options:['Independence','Independance','Independense','Independense']},
    {incorrect:'Millenium',correct:'Millennium',options:['Millennium','Millenium','Milenium','Milennium']},
    {incorrect:'Priviledge',correct:'Privilege',options:['Privilege','Priviledge','Privelege','Privilige']},
    {incorrect:'Goverment',correct:'Government',options:['Government','Goverment','Govermnent','Governmant']},
    {incorrect:'Enviroment',correct:'Environment',options:['Environment','Enviroment','Envirnoment','Envieronment']},
    {incorrect:'Buisness',correct:'Business',options:['Business','Buisness','Bussiness','Bisness']},
    {incorrect:'Grammer',correct:'Grammar',options:['Grammar','Grammer','Gramar','Gramer']},
    {incorrect:'Arguement',correct:'Argument',options:['Argument','Arguement','Arguemant','Argumaent']},
    {incorrect:'Wierd',correct:'Weird',options:['Weird','Wierd','Werd','Weired']},
    {incorrect:'Concious',correct:'Conscious',options:['Conscious','Concious','Consious','Conceous']},
    {incorrect:'Existance',correct:'Existence',options:['Existence','Existance','Existense','Existince']},
  ],

  voiceNarration: [
    {q:'Change to passive: "She writes a letter."',answer:'A letter is written by her.',options:['A letter is written by her.','A letter was written by her.','A letter has been written by her.','A letter written by her.']},
    {q:'Change to passive: "They are playing football."',answer:'Football is being played by them.',options:['Football is being played by them.','Football was being played by them.','Football has been played by them.','Football played by them.']},
    {q:'Change to passive: "He will finish the work."',answer:'The work will be finished by him.',options:['The work will be finished by him.','The work shall be finished by him.','The work is finished by him.','The work would be finished by him.']},
    {q:'Change to passive: "Ram killed a snake."',answer:'A snake was killed by Ram.',options:['A snake was killed by Ram.','A snake is killed by Ram.','A snake had been killed by Ram.','A snake has been killed by Ram.']},
    {q:'Change to passive: "She has completed the project."',answer:'The project has been completed by her.',options:['The project has been completed by her.','The project was completed by her.','The project is completed by her.','The project had been completed by her.']},
    {q:'Change to indirect: He said, "I am happy."',answer:'He said that he was happy.',options:['He said that he was happy.','He said that he is happy.','He told that he was happy.','He said that I am happy.']},
    {q:'Change to indirect: She said, "I will come tomorrow."',answer:'She said that she would come the next day.',options:['She said that she would come the next day.','She said that she will come tomorrow.','She told that she would come tomorrow.','She said she comes the next day.']},
    {q:'Change to indirect: He said to me, "Go home."',answer:'He told me to go home.',options:['He told me to go home.','He said me to go home.','He ordered that I go home.','He told to me to go home.']},
    {q:'Change to indirect: She said, "What a beautiful day!"',answer:'She exclaimed that it was a very beautiful day.',options:['She exclaimed that it was a very beautiful day.','She said what a beautiful day.','She exclaimed that it is a beautiful day.','She told it was a beautiful day.']},
    {q:'Change to indirect: The teacher said, "Do not make noise."',answer:'The teacher told the students not to make noise.',options:['The teacher told the students not to make noise.','The teacher said to don\'t make noise.','The teacher ordered not making noise.','The teacher forbade to make noise.']},
  ],
};
