/**
 * Banking / Finance / Economy Question Bank
 * Based on IBPS PO/Clerk, SBI PO/Clerk, RBI Grade B PYQ patterns.
 * All questions unique — no duplicates.
 */
module.exports = [
  // ── RBI & MONETARY POLICY ──
  {q:'The Reserve Bank of India was established in which year?',a:'1935',b:'1947',c:'1949',d:'1950'},
  {q:'RBI was nationalised in which year?',a:'1949',b:'1935',c:'1947',d:'1951'},
  {q:'The headquarters of RBI is in?',a:'Mumbai',b:'Delhi',c:'Kolkata',d:'Chennai'},
  {q:'Who was the first Governor of the Reserve Bank of India?',a:'Sir Osborne Smith',b:'C.D. Deshmukh',c:'James Taylor',d:'Benegal Rama Rau'},
  {q:'Who was the first Indian Governor of RBI?',a:'C.D. Deshmukh',b:'Sir Osborne Smith',c:'James Taylor',d:'Benegal Rama Rau'},
  {q:'The RBI acts as the banker to?',a:'Government of India and State Governments',b:'Only Central Government',c:'Only State Governments',d:'Only Commercial Banks'},
  {q:'Open Market Operations (OMO) refer to?',a:'Buying and selling of government securities by RBI',b:'Lending to banks',c:'Foreign exchange trading',d:'Setting interest rates'},
  {q:'Monetary Policy Committee (MPC) has how many members?',a:'6',b:'4',c:'8',d:'10'},
  {q:'Reverse Repo Rate is the rate at which?',a:'RBI borrows from commercial banks',b:'RBI lends to commercial banks',c:'Banks lend to customers',d:'Banks borrow from each other'},
  {q:'Bank Rate is the rate at which?',a:'RBI lends long-term funds to commercial banks',b:'Banks lend to customers',c:'RBI borrows from banks',d:'Banks borrow from each other'},
  {q:'Marginal Standing Facility (MSF) rate is usually?',a:'Higher than Repo Rate',b:'Lower than Repo Rate',c:'Equal to Repo Rate',d:'Equal to Bank Rate'},
  {q:'LAF stands for?',a:'Liquidity Adjustment Facility',b:'Lending Adjustment Facility',c:'Liquid Asset Fund',d:'Long-term Adjustment Facility'},
  {q:'SLR stands for?',a:'Statutory Liquidity Ratio',b:'Standard Lending Rate',c:'Savings Liability Ratio',d:'Simple Loan Rate'},
  {q:'CRR requires banks to keep a certain percentage of deposits with?',a:'RBI',b:'Government',c:'SEBI',d:'Finance Ministry'},
  {q:'Priority Sector Lending targets include?',a:'Agriculture, MSME, Education, Housing',b:'Only agriculture',c:'Only education',d:'Only housing'},
  {q:'Inflation targeting by RBI aims to keep inflation at?',a:'4% with ±2% tolerance',b:'2% exactly',c:'6% ceiling',d:'5% floor'},
  // ── BANKING CONCEPTS ──
  {q:'NEFT stands for?',a:'National Electronic Funds Transfer',b:'New Electronic Fund Transfer',c:'National Easy Fund Transfer',d:'Net Electronic Fund Transfer'},
  {q:'RTGS stands for?',a:'Real Time Gross Settlement',b:'Real Total Gross Settlement',c:'Regular Time Gross Settlement',d:'Rapid Transfer Gross Settlement'},
  {q:'IMPS stands for?',a:'Immediate Payment Service',b:'Indian Mobile Payment Service',c:'Instant Money Payment System',d:'Inter-bank Mobile Payment Service'},
  {q:'IFSC code has how many characters?',a:'11',b:'9',c:'10',d:'12'},
  {q:'MICR stands for?',a:'Magnetic Ink Character Recognition',b:'Machine Input Character Recognition',c:'Magnetic Information Code Reader',d:'Machine Ink Code Recognition'},
  {q:'NPA stands for?',a:'Non-Performing Asset',b:'Net Performing Asset',c:'National Payment Authority',d:'Non-Payment Account'},
  {q:'An NPA is a loan where the borrower has not paid interest or principal for?',a:'90 days or more',b:'30 days',c:'60 days',d:'120 days'},
  {q:'CASA stands for?',a:'Current Account Savings Account',b:'Cash and Savings Account',c:'Central Account of Savings Assessment',d:'Credit and Savings Account'},
  {q:'A cheque is valid for how many months from the date of issue?',a:'3 months',b:'6 months',c:'1 month',d:'12 months'},
  {q:'Core Banking Solution (CBS) enables?',a:'Any branch banking across the country',b:'Only local branch banking',c:'Only online banking',d:'Only ATM services'},
  {q:'Demat account is used for?',a:'Holding shares in electronic form',b:'Fixed deposits',c:'Savings only',d:'Loans only'},
  {q:'FDI stands for?',a:'Foreign Direct Investment',b:'Financial Development Investment',c:'Federal Deposit Insurance',d:'Fund Distribution Index'},
  {q:'FII stands for?',a:'Foreign Institutional Investor',b:'Financial Industry Index',c:'Federal Investment Institute',d:'Fund Insurance Institution'},
  {q:'UPI stands for?',a:'Unified Payments Interface',b:'Universal Payment Integration',c:'United Payment Infrastructure',d:'Unified Processing Interface'},
  {q:'BHIM app stands for?',a:'Bharat Interface for Money',b:'Banking and Handling of Indian Money',c:'Bharat Integrated Money',d:'Banking Hub of Indian Market'},
  {q:'Jan Dhan Yojana was launched in which year?',a:'2014',b:'2015',c:'2016',d:'2013'},
  {q:'MUDRA stands for?',a:'Micro Units Development and Refinance Agency',b:'Monetary Units Development Agency',c:'Micro Units Distribution and Refinance Authority',d:'Monetary Union Development and Research Agency'},
  {q:'Under MUDRA, Shishu loan limit is?',a:'Up to ₹50,000',b:'Up to ₹5 lakh',c:'Up to ₹10 lakh',d:'Up to ₹1 lakh'},
  {q:'Under MUDRA, Kishor loan range is?',a:'₹50,001 to ₹5 lakh',b:'₹5 lakh to ₹10 lakh',c:'Up to ₹50,000',d:'₹1 lakh to ₹5 lakh'},
  {q:'Under MUDRA, Tarun loan range is?',a:'₹5 lakh to ₹10 lakh',b:'₹50,001 to ₹5 lakh',c:'Up to ₹5 lakh',d:'₹10 lakh to ₹20 lakh'},
  // ── INSTITUTIONS & REGULATIONS ──
  {q:'NABARD stands for?',a:'National Bank for Agriculture and Rural Development',b:'National Board for Agricultural Research',c:'National Bureau of Agricultural Research',d:'National Bank for Agrarian Distribution'},
  {q:'NABARD was established in which year?',a:'1982',b:'1969',c:'1975',d:'1990'},
  {q:'SIDBI stands for?',a:'Small Industries Development Bank of India',b:'State Industries Development Bank',c:'Social Investment Development Bank',d:'Small Infrastructure Development Bureau'},
  {q:'EXIM Bank deals with?',a:'Export and Import financing',b:'Domestic banking only',c:'Insurance only',d:'Mutual funds'},
  {q:'DICGC insures bank deposits up to?',a:'₹5 lakh',b:'₹1 lakh',c:'₹10 lakh',d:'₹50 lakh'},
  {q:'Payment Banks can accept deposits up to?',a:'₹2 lakh per customer',b:'₹1 lakh',c:'₹5 lakh',d:'₹10 lakh'},
  {q:'Which committee recommended setting up of Payment Banks?',a:'Nachiket Mor Committee',b:'Raghuram Rajan Committee',c:'Urjit Patel Committee',d:'P.J. Nayak Committee'},
  {q:'Basel III norms are related to?',a:'Bank capital adequacy and risk management',b:'Tax regulations',c:'Insurance standards',d:'Foreign trade'},
  {q:'CIBIL stands for?',a:'Credit Information Bureau (India) Limited',b:'Central India Banking Investment Limited',c:'Credit Insurance Bureau Limited',d:'Central Information Bureau Limited'},
  {q:'SWIFT stands for?',a:'Society for Worldwide Interbank Financial Telecommunication',b:'Standard Worldwide Internet Financial Transfer',c:'Secure Worldwide Interbank Fund Transfer',d:'Society for World Internet Financial Technology'},
  // ── FINANCIAL MARKETS ──
  {q:'SEBI was established in which year (statutory)?',a:'1992',b:'1988',c:'1995',d:'1990'},
  {q:'BSE stands for?',a:'Bombay Stock Exchange',b:'Banking Securities Exchange',c:'Bond and Securities Exchange',d:'Business Stock Exchange'},
  {q:'NSE stands for?',a:'National Stock Exchange',b:'New Securities Exchange',c:'National Savings Exchange',d:'National Share Enterprise'},
  {q:'The SENSEX is the benchmark index of?',a:'BSE',b:'NSE',c:'MCX',d:'CDSL'},
  {q:'NIFTY 50 is the benchmark index of?',a:'NSE',b:'BSE',c:'SEBI',d:'RBI'},
  {q:'IPO stands for?',a:'Initial Public Offering',b:'Indian Public Offering',c:'Initial Private Offering',d:'Investment Public Offer'},
  {q:'Mutual funds are regulated by?',a:'SEBI',b:'RBI',c:'IRDA',d:'PFRDA'},
  {q:'NAV stands for?',a:'Net Asset Value',b:'New Asset Value',c:'Net Annual Value',d:'National Asset Valuation'},
  {q:'SIP stands for?',a:'Systematic Investment Plan',b:'Standard Investment Plan',c:'Simple Interest Plan',d:'Special Investment Programme'},
  {q:'Treasury Bills are issued for a maximum period of?',a:'364 days',b:'1 year',c:'5 years',d:'10 years'},
  {q:'NSDL stands for?',a:'National Securities Depository Limited',b:'National Savings Depository Limited',c:'New Securities Distribution League',d:'National Share Development Limited'},
  // ── INSURANCE ──
  {q:'IRDA stands for?',a:'Insurance Regulatory and Development Authority',b:'Indian Revenue Development Authority',c:'Insurance Registration Agency',d:'Investment Regulatory Authority'},
  {q:'LIC was established in which year?',a:'1956',b:'1947',c:'1969',d:'1961'},
  {q:'PMJJBY premium is?',a:'₹436 per annum',b:'₹330 per annum',c:'₹12 per annum',d:'₹500 per annum'},
  {q:'PMSBY premium is?',a:'₹20 per annum',b:'₹12 per annum',c:'₹330 per annum',d:'₹100 per annum'},
  {q:'APY stands for?',a:'Atal Pension Yojana',b:'Ayushman Pension Yojana',c:'Annual Pension Yield',d:'Agricultural Pension Yojana'},
  {q:'Reinsurance means?',a:'Insurance of insurance companies',b:'Renewal of insurance',c:'Reinstating lapsed policies',d:'Insurance for senior citizens'},
  // ── GOVT SCHEMES & ECONOMY ──
  {q:'GST was implemented in India on?',a:'1 July 2017',b:'1 April 2017',c:'1 January 2018',d:'1 October 2017'},
  {q:'How many main GST slabs are there?',a:'4 (5%, 12%, 18%, 28%)',b:'3',c:'5',d:'2'},
  {q:'The GST Council is chaired by?',a:'Union Finance Minister',b:'Prime Minister',c:'RBI Governor',d:'NITI Aayog CEO'},
  {q:'Fiscal deficit is?',a:'Total expenditure minus total receipts excluding borrowings',b:'Revenue expenditure minus revenue receipts',c:'Capital expenditure minus capital receipts',d:'Total income minus total expenditure'},
  {q:'Revenue deficit is?',a:'Revenue expenditure minus revenue receipts',b:'Total expenditure minus total receipts',c:'Capital expenditure minus capital receipts',d:'Fiscal deficit minus borrowings'},
  {q:'Primary deficit is?',a:'Fiscal deficit minus interest payments',b:'Revenue deficit minus interest',c:'Total deficit minus interest',d:'Budget deficit minus borrowings'},
  {q:'Disinvestment refers to?',a:'Government selling its stake in PSUs',b:'Foreign investors leaving India',c:'Closing of industries',d:'Reduction in bank deposits'},
  {q:'Make in India was launched in which year?',a:'2014',b:'2015',c:'2016',d:'2013'},
  {q:'Demonetisation of ₹500 and ₹1000 notes was announced on?',a:'8 November 2016',b:'1 January 2017',c:'15 August 2016',d:'26 January 2017'},
  {q:'WPI stands for?',a:'Wholesale Price Index',b:'World Price Index',c:'Weighted Price Index',d:'Wholesale Product Index'},
  {q:'CPI stands for?',a:'Consumer Price Index',b:'Central Price Index',c:'Common Product Index',d:'Consumer Product Index'},
  {q:'HDI is published by?',a:'UNDP',b:'World Bank',c:'IMF',d:'WHO'},
  {q:'MGNREGA guarantees minimum employment for?',a:'100 days per year',b:'150 days',c:'200 days',d:'365 days'},
  // ── INTERNATIONAL ORGANISATIONS ──
  {q:'IMF headquarters is located in?',a:'Washington D.C.',b:'New York',c:'Geneva',d:'London'},
  {q:'SDR is issued by?',a:'IMF',b:'World Bank',c:'WTO',d:'ADB'},
  {q:'ADB headquarters is in?',a:'Manila, Philippines',b:'Tokyo, Japan',c:'Beijing, China',d:'Singapore'},
  {q:'AIIB stands for?',a:'Asian Infrastructure Investment Bank',b:'Asian International Investment Bureau',c:'Asian Industrial Investment Bank',d:'African Infrastructure Investment Bank'},
  {q:'NDB (New Development Bank) was established by?',a:'BRICS nations',b:'G7 nations',c:'ASEAN nations',d:'G20 nations'},
  {q:'WTO was established in which year?',a:'1995',b:'1990',c:'2000',d:'1985'},
  // ── INDIAN BANKING HISTORY ──
  {q:'Bank nationalisation in India first happened in?',a:'1969',b:'1947',c:'1955',d:'1980'},
  {q:'How many banks were nationalised in 1969?',a:'14',b:'10',c:'20',d:'6'},
  {q:'How many banks were nationalised in 1980?',a:'6',b:'14',c:'10',d:'20'},
  {q:'SBI was formed in which year?',a:'1955',b:'1935',c:'1947',d:'1969'},
  {q:'SBI was formerly known as?',a:'Imperial Bank of India',b:'Royal Bank of India',c:'Presidency Bank',d:'British Bank of India'},
  {q:'The tagline of SBI is?',a:'With you all the way',b:'Good People to Bank With',c:'Together We Can',d:'Tradition of Trust'},
  {q:'The tagline of Bank of Baroda is?',a:'India\'s International Bank',b:'The Name You Can Bank Upon',c:'Good People to Bank With',d:'Serving to Empower'},
  {q:'The tagline of PNB is?',a:'The Name You Can Bank Upon',b:'India\'s International Bank',c:'Good People to Bank With',d:'Together We Can'},
  // ── DIGITAL BANKING ──
  {q:'NPCI stands for?',a:'National Payments Corporation of India',b:'National Public Credit Institute',c:'National Payment and Credit Infrastructure',d:'National Processing Corporation of India'},
  {q:'NPCI manages which payment systems?',a:'UPI, IMPS, RuPay, NACH, NFS',b:'Only UPI',c:'Only ATM network',d:'Only RTGS'},
  {q:'RuPay card was launched under?',a:'NPCI',b:'RBI',c:'VISA',d:'MasterCard'},
  {q:'White Label ATMs are operated by?',a:'Non-bank entities',b:'Banks only',c:'Government',d:'RBI'},
  // ── ACTS ──
  {q:'The Banking Regulation Act was enacted in?',a:'1949',b:'1935',c:'1947',d:'1969'},
  {q:'The Negotiable Instruments Act was enacted in?',a:'1881',b:'1949',c:'1935',d:'1872'},
  {q:'FEMA stands for?',a:'Foreign Exchange Management Act',b:'Financial Exchange Management Act',c:'Federal Exchange Monetary Act',d:'Foreign Economic Management Authority'},
  {q:'FEMA was enacted in which year?',a:'1999',b:'1973',c:'2000',d:'1991'},
  {q:'The Insolvency and Bankruptcy Code (IBC) was enacted in?',a:'2016',b:'2014',c:'2018',d:'2010'},
  {q:'SARFAESI Act deals with?',a:'Recovery of bad loans by banks',b:'Tax collection',c:'Insurance regulation',d:'Foreign trade'},
  // ── TAXES & PERSONAL FINANCE ──
  {q:'TDS stands for?',a:'Tax Deducted at Source',b:'Total Deduction System',c:'Tax Distribution Service',d:'Transfer Deposit System'},
  {q:'PAN stands for?',a:'Permanent Account Number',b:'Public Account Number',c:'Private Account Number',d:'Personal Authentication Number'},
  {q:'PPF stands for?',a:'Public Provident Fund',b:'Personal Provident Fund',c:'Public Payment Fund',d:'Postal Provident Fund'},
  {q:'PPF has a lock-in period of?',a:'15 years',b:'5 years',c:'10 years',d:'20 years'},
  {q:'NPS is regulated by?',a:'PFRDA',b:'SEBI',c:'RBI',d:'IRDA'},
  {q:'Section 80C of IT Act allows deduction up to?',a:'₹1.5 lakh',b:'₹1 lakh',c:'₹2 lakh',d:'₹50,000'},
  {q:'Short-term capital gains on equity shares (with STT) are taxed at?',a:'15%',b:'20%',c:'10%',d:'30%'},
  // ── MISCELLANEOUS ──
  {q:'ATM stands for?',a:'Automated Teller Machine',b:'All Time Money',c:'Any Time Money',d:'Automated Transfer Machine'},
  {q:'EMI stands for?',a:'Equated Monthly Instalment',b:'Expected Monthly Income',c:'Equal Monthly Investment',d:'Estimated Monthly Interest'},
  {q:'A Scheduled Bank is one that?',a:'Is included in the Second Schedule of the RBI Act',b:'Operates only on working days',c:'Has fixed interest rates',d:'Lends only to government'},
  {q:'The minimum CRAR required for Indian banks is?',a:'9%',b:'8%',c:'10%',d:'12%'},
  {q:'Bancassurance means?',a:'Selling insurance products through banks',b:'Banking for insurance companies',c:'Insurance for banks',d:'Bank guarantee for insurance'},
  {q:'A stale cheque is one that is?',a:'More than 3 months old',b:'Post-dated',c:'Unsigned',d:'Crossed'},
  {q:'A post-dated cheque is?',a:'A cheque bearing a future date',b:'An expired cheque',c:'A cheque without a date',d:'A dishonoured cheque'},
  {q:'Overdraft facility is available on?',a:'Current account',b:'Savings account',c:'Fixed deposit',d:'Recurring deposit'},
  {q:'What does KYC stand for?',a:'Know Your Customer',b:'Keep Your Cash',c:'Know Your Credit',d:'Key Yield Certificate'},
  {q:'What does CRR stand for?',a:'Cash Reserve Ratio',b:'Current Revenue Rate',c:'Cost Recovery Rate',d:'Credit Risk Ratio'},
  {q:'Repo Rate is the rate at which?',a:'RBI lends to commercial banks',b:'Banks lend to customers',c:'RBI borrows from banks',d:'Banks borrow from each other'},
  {q:'Which bank is called the "Banker\'s Bank"?',a:'RBI',b:'SBI',c:'ICICI',d:'HDFC'},
  {q:'The full form of SEBI is?',a:'Securities and Exchange Board of India',b:'Stock Exchange Board of India',c:'Securities and Equity Board of India',d:'Stock and Exchange Bureau of India'},
  {q:'Who presents the Union Budget in Parliament?',a:'Finance Minister',b:'Prime Minister',c:'President',d:'RBI Governor'},
  {q:'CRISIL stands for?',a:'Credit Rating Information Services of India Limited',b:'Credit Research and Investment Services',c:'Central Rating Information Services',d:'Credit Rating Institute of India'},
  {q:'FPO in the context of shares stands for?',a:'Follow-on Public Offer',b:'First Public Offering',c:'Financial Public Offer',d:'Fund Public Offering'},
  {q:'What is the full form of IFSC?',a:'Indian Financial System Code',b:'International Fund System Code',c:'Indian Fund Security Code',d:'International Financial Security Code'},
  {q:'Max deposit insured by DICGC?',a:'₹5 lakhs',b:'₹1 lakh',c:'₹10 lakhs',d:'₹50 lakhs'},
  {q:'What does GDP stand for?',a:'Gross Domestic Product',b:'General Domestic Product',c:'Gross Development Product',d:'General Development Plan'},
  {q:'Who heads the RBI?',a:'Governor',b:'Chairman',c:'President',d:'Director'},
  {q:'SEBI primarily regulates?',a:'Securities Market',b:'Banking Sector',c:'Insurance Sector',d:'Foreign Trade'},
  {q:'The Finance Commission is constituted under which Article?',a:'Article 280',b:'Article 256',c:'Article 300',d:'Article 312'},
  {q:'The monetary policy is announced by?',a:'RBI',b:'Finance Ministry',c:'SEBI',d:'NITI Aayog'},
  {q:'Small Finance Banks are designed to serve?',a:'Unserved and underserved sections',b:'Large corporates only',c:'Foreign investors',d:'Government departments'},
  {q:'The Banking Ombudsman scheme was introduced by?',a:'RBI',b:'SEBI',c:'Government of India',d:'NABARD'},
  {q:'Long-term capital gains on equity above ₹1 lakh are taxed at?',a:'10%',b:'15%',c:'20%',d:'5%'},
  {q:'NHB stands for?',a:'National Housing Bank',b:'National Highway Board',c:'New Housing Bureau',d:'National Health Board'},
  {q:'E-KYC uses which technology?',a:'Aadhaar-based biometric authentication',b:'Passport scanning',c:'PAN card only',d:'Driving license'},
  {q:'Hawala is?',a:'An illegal money transfer system',b:'A legal banking channel',c:'A government scheme',d:'A type of insurance'},
  {q:'SDR stands for?',a:'Special Drawing Rights',b:'Standard Drawing Rights',c:'Special Deposit Rate',d:'Standard Deposit Ratio'},
  {q:'What is the minimum balance for BSBD (Basic Savings Bank Deposit) account?',a:'Zero balance',b:'₹500',c:'₹1000',d:'₹2000'},
  {q:'GATT stands for?',a:'General Agreement on Tariffs and Trade',b:'Global Agreement on Trade and Tariffs',c:'General Authority for Tariff and Trade',d:'Global Authority on Trade and Taxation'},
  {q:'A bond is?',a:'A debt instrument',b:'An equity share',c:'A savings account',d:'A fixed deposit'},
  {q:'G-Sec stands for?',a:'Government Securities',b:'General Securities',c:'Growth Securities',d:'Guaranteed Securities'},
  {q:'DICGC stands for?',a:'Deposit Insurance and Credit Guarantee Corporation',b:'Deposit and Investment Corporation',c:'District Insurance Group Company',d:'Deposit and Income Credit Group'},
  {q:'PMLA was enacted in?',a:'2002',b:'2005',c:'2010',d:'1999'},
  {q:'NCLT stands for?',a:'National Company Law Tribunal',b:'National Credit and Loan Tribunal',c:'National Corporate Law Tribunal',d:'National Commercial Lending Trust'},
  {q:'Digital Lending refers to?',a:'Credit through online/mobile platforms',b:'Currency printing',c:'Physical loan disbursement',d:'ATM cash withdrawal'},
  {q:'Start-up India was launched in which year?',a:'2016',b:'2014',c:'2015',d:'2017'},
  {q:'BPL stands for?',a:'Below Poverty Line',b:'Basic Poverty Level',c:'Below Production Level',d:'Basic Price Line'},
  {q:'PPP stands for (economics)?',a:'Purchasing Power Parity',b:'Public-Private Partnership',c:'Both depending on context',d:'Personal Payment Plan'},
  {q:'Capital gains tax is levied on?',a:'Profit from sale of assets',b:'Salary income',c:'Business income',d:'Rental income only'},
  {q:'Credit rating agencies in India include?',a:'CRISIL, ICRA, CARE',b:'Only CRISIL',c:'RBI and SEBI',d:'BSE and NSE'},
  {q:'PIN stands for?',a:'Personal Identification Number',b:'Permanent Identification Number',c:'Private Internet Number',d:'Personal Information Number'},
  {q:'CDSL stands for?',a:'Central Depository Services Limited',b:'Credit Depository Systems Limited',c:'Central Distribution Services Limited',d:'Capital Depository Services Limited'},
  {q:'The Gadgil Committee recommended?',a:'Lead Bank Scheme',b:'Payment Banks',c:'Basel Norms',d:'NPA classification'},
  {q:'Brown Label ATMs are?',a:'Owned by service provider but bank-branded',b:'Only banks',c:'Only non-banks',d:'Government owned'},
  {q:'FEMA replaced which earlier act?',a:'FERA',b:'Companies Act',c:'Banking Regulation Act',d:'Securities Act'},
  {q:'World Bank Group consists of how many institutions?',a:'5',b:'3',c:'4',d:'6'},
  {q:'PAN card is issued by?',a:'Income Tax Department',b:'RBI',c:'SEBI',d:'Finance Ministry'},
  {q:'NPS stands for?',a:'National Pension System',b:'New Pension Scheme',c:'National Payment System',d:'Net Payment Service'},
  {q:'The minimum CRR that RBI can prescribe is?',a:'3%',b:'0%',c:'5%',d:'10%'},
  {q:'The oldest commercial bank in India still existing is?',a:'SBI (formerly Imperial Bank)',b:'Bank of Baroda',c:'Punjab National Bank',d:'Canara Bank'},
];
