/**
 * General Knowledge / General Awareness Question Bank
 * Based on SSC CGL/CHSL/MTS/GD, RRB NTPC/Group D, IBPS/SBI PYQ patterns.
 * Covers: Indian History, Geography, Polity, Economy, Science, Culture, Sports, Awards.
 * All questions are unique — no duplicates within or across sections.
 */
module.exports = [
  // ── INDIAN HISTORY: Ancient ──
  {q:'The Indus Valley Civilization flourished during which age?',a:'Bronze Age',b:'Iron Age',c:'Stone Age',d:'Copper Age'},
  {q:'Mohenjo-daro is situated in which present-day country?',a:'Pakistan',b:'India',c:'Afghanistan',d:'Bangladesh'},
  {q:'The Great Bath was discovered at which Indus Valley site?',a:'Mohenjo-daro',b:'Harappa',c:'Lothal',d:'Kalibangan'},
  {q:'Which Vedic text is the oldest?',a:'Rigveda',b:'Samaveda',c:'Yajurveda',d:'Atharvaveda'},
  {q:'The ancient city of Taxila was located in which modern country?',a:'Pakistan',b:'India',c:'Nepal',d:'Sri Lanka'},
  {q:'Who founded the Maurya Empire?',a:'Chandragupta Maurya',b:'Ashoka',c:'Bindusara',d:'Brihadratha'},
  {q:'The famous Arthashastra was written by whom?',a:'Kautilya',b:'Kalidasa',c:'Banabhatta',d:'Vishakhadatta'},
  {q:'Ashoka embraced Buddhism after which battle?',a:'Kalinga War',b:'Hydaspes',c:'Talikota',d:'Panipat'},
  {q:'The Ajanta Caves are famous for paintings related to which religion?',a:'Buddhism',b:'Hinduism',c:'Jainism',d:'Islam'},
  {q:'The Gupta period is known as the Golden Age of India. Who was the founder of the Gupta dynasty?',a:'Sri Gupta',b:'Chandragupta I',c:'Samudragupta',d:'Kumaragupta'},
  {q:'Nalanda University was established during which dynasty?',a:'Gupta',b:'Maurya',c:'Mughal',d:'Chola'},
  {q:'The Iron Pillar in Delhi was erected during the reign of which king?',a:'Chandragupta II',b:'Ashoka',c:'Samudragupta',d:'Harsha'},
  {q:'Aryabhata, the famous mathematician, lived during which period?',a:'Gupta period',b:'Maurya period',c:'Mughal period',d:'Vedic period'},
  {q:'The Ellora Caves are located in which Indian state?',a:'Maharashtra',b:'Madhya Pradesh',c:'Karnataka',d:'Rajasthan'},
  {q:'Who was the author of the Sanskrit play Shakuntala?',a:'Kalidasa',b:'Bhasa',c:'Shudraka',d:'Bharavi'},
  // ── INDIAN HISTORY: Medieval ──
  {q:'The Delhi Sultanate was established in which year?',a:'1206',b:'1192',c:'1256',d:'1290'},
  {q:'Who built the Qutub Minar in Delhi?',a:'Qutb-ud-din Aibak',b:'Iltutmish',c:'Alauddin Khalji',d:'Muhammad bin Tughluq'},
  {q:'Which Mughal emperor built the Taj Mahal?',a:'Shah Jahan',b:'Akbar',c:'Jahangir',d:'Aurangzeb'},
  {q:'The Battle of Panipat in 1526 was fought between Babur and whom?',a:'Ibrahim Lodi',b:'Rana Sanga',c:'Hemu',d:'Sher Shah Suri'},
  {q:'Akbar\'s revenue minister was known as?',a:'Todar Mal',b:'Birbal',c:'Abul Fazl',d:'Man Singh'},
  {q:'The Vijayanagara Empire was founded by whom?',a:'Harihara and Bukka',b:'Krishna Deva Raya',c:'Deva Raya II',d:'Rama Raya'},
  {q:'Who introduced the Mansabdari system?',a:'Akbar',b:'Babur',c:'Shah Jahan',d:'Aurangzeb'},
  {q:'Shivaji was the founder of which empire?',a:'Maratha Empire',b:'Mughal Empire',c:'Vijayanagara Empire',d:'Sikh Empire'},
  {q:'The famous Kohinoor diamond was originally from which mine?',a:'Kollur Mine',b:'Golconda Mine',c:'Panna Mine',d:'Wajrakarur Mine'},
  {q:'Who was the last Mughal emperor?',a:'Bahadur Shah Zafar',b:'Aurangzeb',c:'Shah Alam II',d:'Muhammad Shah'},
  // ── INDIAN HISTORY: Modern / Freedom Movement ──
  {q:'The Battle of Plassey was fought in which year?',a:'1757',b:'1764',c:'1857',d:'1799'},
  {q:'Who is known as the Father of the Indian National Congress?',a:'A.O. Hume',b:'W.C. Bannerjee',c:'Dadabhai Naoroji',d:'Surendranath Banerjee'},
  {q:'The Jallianwala Bagh massacre took place in which year?',a:'1919',b:'1920',c:'1921',d:'1918'},
  {q:'Who gave the slogan "Do or Die"?',a:'Mahatma Gandhi',b:'Subhas Chandra Bose',c:'Jawaharlal Nehru',d:'Bal Gangadhar Tilak'},
  {q:'The Quit India Movement was launched in which year?',a:'1942',b:'1940',c:'1945',d:'1947'},
  {q:'Who was the first Governor-General of independent India?',a:'Lord Mountbatten',b:'C. Rajagopalachari',c:'Jawaharlal Nehru',d:'Dr. Rajendra Prasad'},
  {q:'The Indian National Army was founded by whom?',a:'Subhas Chandra Bose',b:'Rash Behari Bose',c:'Mohan Singh',d:'Captain Lakshmi'},
  {q:'The Partition of Bengal took place in which year?',a:'1905',b:'1911',c:'1919',d:'1935'},
  {q:'Who is known as the "Iron Man of India"?',a:'Sardar Vallabhbhai Patel',b:'Jawaharlal Nehru',c:'Lal Bahadur Shastri',d:'B.R. Ambedkar'},
  {q:'The Rowlatt Act was passed in which year?',a:'1919',b:'1920',c:'1921',d:'1935'},
  {q:'Who founded the Arya Samaj?',a:'Swami Dayanand Saraswati',b:'Swami Vivekananda',c:'Raja Ram Mohan Roy',d:'Ishwar Chandra Vidyasagar'},
  {q:'The First War of Indian Independence occurred in which year?',a:'1857',b:'1857',c:'1799',d:'1764'},
  {q:'Who gave the slogan "Inquilab Zindabad"?',a:'Bhagat Singh',b:'Chandra Shekhar Azad',c:'Lala Lajpat Rai',d:'Subhas Chandra Bose'},
  {q:'Mahatma Gandhi launched the Salt March (Dandi March) in which year?',a:'1930',b:'1931',c:'1932',d:'1929'},
  {q:'Who was the first woman President of the Indian National Congress?',a:'Annie Besant',b:'Sarojini Naidu',c:'Kamala Nehru',d:'Vijaya Lakshmi Pandit'},
  {q:'The Simon Commission visited India in which year?',a:'1928',b:'1930',c:'1935',d:'1919'},
  {q:'Who is known as the "Grand Old Man of India"?',a:'Dadabhai Naoroji',b:'Gopal Krishna Gokhale',c:'Mahatma Gandhi',d:'Bal Gangadhar Tilak'},
  {q:'The Montagu-Chelmsford Reforms were introduced in which year?',a:'1919',b:'1909',c:'1935',d:'1947'},
  {q:'Who led the Bardoli Satyagraha?',a:'Sardar Vallabhbhai Patel',b:'Mahatma Gandhi',c:'Jawaharlal Nehru',d:'Rajendra Prasad'},
  {q:'The Dandi March covered a distance of approximately how many kilometres?',a:'385 km',b:'241 km',c:'500 km',d:'300 km'},
  // ── INDIAN GEOGRAPHY ──
  {q:'Which is the longest river in India?',a:'Ganga',b:'Yamuna',c:'Godavari',d:'Brahmaputra'},
  {q:'The Deccan Plateau is located in which part of India?',a:'Southern India',b:'Northern India',c:'Eastern India',d:'Western India'},
  {q:'Which Indian state has the longest coastline?',a:'Gujarat',b:'Maharashtra',c:'Tamil Nadu',d:'Kerala'},
  {q:'The Thar Desert is located in which Indian state?',a:'Rajasthan',b:'Gujarat',c:'Haryana',d:'Punjab'},
  {q:'Mount Everest is located in which mountain range?',a:'Himalayas',b:'Andes',c:'Alps',d:'Rockies'},
  {q:'Which is the largest freshwater lake in India?',a:'Wular Lake',b:'Dal Lake',c:'Chilika Lake',d:'Sambhar Lake'},
  {q:'The Western Ghats are also known as?',a:'Sahyadri',b:'Vindhya',c:'Satpura',d:'Aravalli'},
  {q:'Which river is known as the "Sorrow of Bihar"?',a:'Kosi',b:'Gandak',c:'Son',d:'Mahananda'},
  {q:'The Sundarbans delta is formed by which rivers?',a:'Ganga and Brahmaputra',b:'Ganga and Yamuna',c:'Godavari and Krishna',d:'Mahanadi and Cauvery'},
  {q:'Which is the smallest state in India by area?',a:'Goa',b:'Sikkim',c:'Tripura',d:'Mizoram'},
  {q:'Nanda Devi peak is located in which state?',a:'Uttarakhand',b:'Himachal Pradesh',c:'Sikkim',d:'Jammu & Kashmir'},
  {q:'The Chilika Lake is located in which state?',a:'Odisha',b:'Andhra Pradesh',c:'Tamil Nadu',d:'Kerala'},
  {q:'Which is the highest plateau in the world?',a:'Tibetan Plateau',b:'Deccan Plateau',c:'Columbia Plateau',d:'Altiplano'},
  {q:'The Palk Strait separates India from which country?',a:'Sri Lanka',b:'Maldives',c:'Myanmar',d:'Bangladesh'},
  {q:'Which city is known as the "Silicon Valley of India"?',a:'Bengaluru',b:'Hyderabad',c:'Pune',d:'Chennai'},
  {q:'Which Indian city receives the highest annual rainfall?',a:'Mawsynram',b:'Cherrapunji',c:'Mumbai',d:'Agumbe'},
  {q:'The Andaman and Nicobar Islands are located in which body of water?',a:'Bay of Bengal',b:'Arabian Sea',c:'Indian Ocean',d:'Pacific Ocean'},
  {q:'Which pass connects Kashmir with Ladakh?',a:'Zoji La',b:'Shipki La',c:'Rohtang Pass',d:'Khyber Pass'},
  {q:'The Cauvery River originates from which hill?',a:'Talakaveri',b:'Mahabaleshwar',c:'Amarkantak',d:'Gangotri'},
  {q:'Which is the largest delta in the world?',a:'Sundarbans Delta',b:'Nile Delta',c:'Mekong Delta',d:'Mississippi Delta'},
  // ── INDIAN POLITY & CONSTITUTION ──
  {q:'Who is known as the Father of the Indian Constitution?',a:'Dr. B.R. Ambedkar',b:'Mahatma Gandhi',c:'Jawaharlal Nehru',d:'Sardar Patel'},
  {q:'The Indian Constitution was adopted on which date?',a:'26 November 1949',b:'26 January 1950',c:'15 August 1947',d:'2 October 1950'},
  {q:'How many Fundamental Rights are guaranteed by the Indian Constitution?',a:'6',b:'7',c:'5',d:'8'},
  {q:'The Preamble of the Indian Constitution begins with which phrase?',a:'"We, the people of India"',b:'"We, the citizens of India"',c:'"In the name of God"',d:'"For the Republic of India"'},
  {q:'What is the minimum age to become the President of India?',a:'35 years',b:'30 years',c:'25 years',d:'40 years'},
  {q:'The Vice President of India is elected by whom?',a:'Members of both Houses of Parliament',b:'Members of Lok Sabha only',c:'Electoral College',d:'State Legislatures'},
  {q:'Which article of the Indian Constitution deals with Fundamental Rights?',a:'Articles 12-35',b:'Articles 36-51',c:'Articles 51A',d:'Articles 1-11'},
  {q:'The Right to Education was added by which Constitutional Amendment?',a:'86th Amendment',b:'42nd Amendment',c:'73rd Amendment',d:'44th Amendment'},
  {q:'How many members can be nominated to the Rajya Sabha by the President?',a:'12',b:'10',c:'14',d:'2'},
  {q:'The concept of Directive Principles of State Policy was borrowed from which country?',a:'Ireland',b:'UK',c:'USA',d:'France'},
  {q:'Which Schedule of the Indian Constitution deals with the allocation of seats in Rajya Sabha?',a:'Fourth Schedule',b:'Third Schedule',c:'Fifth Schedule',d:'Seventh Schedule'},
  {q:'The 73rd Constitutional Amendment is related to?',a:'Panchayati Raj',b:'Municipalities',c:'Right to Education',d:'Anti-Defection'},
  {q:'Article 370 was related to which state?',a:'Jammu & Kashmir',b:'Nagaland',c:'Mizoram',d:'Sikkim'},
  {q:'The Chief Justice of India is appointed by whom?',a:'President of India',b:'Prime Minister',c:'Parliament',d:'Law Minister'},
  {q:'The maximum strength of the Lok Sabha is?',a:'552',b:'545',c:'500',d:'600'},
  // ── ECONOMICS ──
  {q:'What does GDP stand for?',a:'Gross Domestic Product',b:'General Domestic Product',c:'Gross Development Product',d:'General Development Plan'},
  {q:'The Reserve Bank of India was established in which year?',a:'1935',b:'1947',c:'1949',d:'1950'},
  {q:'Who is called the father of Indian economic reform?',a:'Manmohan Singh',b:'P. Chidambaram',c:'Pranab Mukherjee',d:'Yashwant Sinha'},
  {q:'NABARD stands for?',a:'National Bank for Agriculture and Rural Development',b:'National Board for Agricultural Research and Development',c:'National Bureau of Agricultural Research and Development',d:'National Bank for Agrarian and Rural Distribution'},
  {q:'The Planning Commission of India was replaced by which institution?',a:'NITI Aayog',b:'Finance Commission',c:'National Development Council',d:'NABARD'},
  {q:'In which year was GST implemented in India?',a:'2017',b:'2016',c:'2018',d:'2015'},
  {q:'Which tax is collected by the Central Government?',a:'Income Tax',b:'Property Tax',c:'Water Tax',d:'Octroi'},
  {q:'The first Five Year Plan in India started in which year?',a:'1951',b:'1947',c:'1950',d:'1955'},
  {q:'What is the full form of SEBI?',a:'Securities and Exchange Board of India',b:'Stock Exchange Board of India',c:'Securities and Equity Board of India',d:'Stock and Exchange Bureau of India'},
  {q:'Fiscal deficit is defined as the difference between?',a:'Total expenditure and total receipts excluding borrowings',b:'Revenue expenditure and revenue receipts',c:'Capital expenditure and capital receipts',d:'Total income and total expenditure'},
  {q:'The Goods and Services Tax (GST) is levied on?',a:'Supply of goods and services',b:'Manufacturing only',c:'Import only',d:'Services only'},
  {q:'Who presents the Union Budget in Parliament?',a:'Finance Minister',b:'Prime Minister',c:'President',d:'RBI Governor'},
  {q:'The National Income of India is measured by which organisation?',a:'Central Statistics Office',b:'NITI Aayog',c:'Reserve Bank of India',d:'Finance Ministry'},
  {q:'What is the currency of Japan?',a:'Yen',b:'Won',c:'Yuan',d:'Ringgit'},
  {q:'The headquarters of the World Bank is located in?',a:'Washington D.C.',b:'New York',c:'Geneva',d:'London'},
  // ── GENERAL SCIENCE (for GK sections) ──
  {q:'Which vitamin is produced when human skin is exposed to sunlight?',a:'Vitamin D',b:'Vitamin A',c:'Vitamin C',d:'Vitamin B12'},
  {q:'What is the chemical symbol for gold?',a:'Au',b:'Ag',c:'Fe',d:'Cu'},
  {q:'Which planet is known as the Red Planet?',a:'Mars',b:'Venus',c:'Jupiter',d:'Mercury'},
  {q:'What is the largest planet in our solar system?',a:'Jupiter',b:'Saturn',c:'Neptune',d:'Uranus'},
  {q:'Which gas is most abundant in Earth\'s atmosphere?',a:'Nitrogen',b:'Oxygen',c:'Carbon Dioxide',d:'Argon'},
  {q:'DNA stands for?',a:'Deoxyribonucleic Acid',b:'Diribonucleic Acid',c:'Deoxyribose Nucleic Acetate',d:'Dual Nucleic Acid'},
  {q:'The human body has how many pairs of chromosomes?',a:'23',b:'22',c:'46',d:'24'},
  {q:'Which organ in the human body produces insulin?',a:'Pancreas',b:'Liver',c:'Kidney',d:'Heart'},
  {q:'What is the boiling point of water at sea level?',a:'100°C',b:'90°C',c:'110°C',d:'80°C'},
  {q:'Which blood group is the universal donor?',a:'O negative',b:'AB positive',c:'A positive',d:'B negative'},
  {q:'The speed of light is approximately?',a:'3 × 10⁸ m/s',b:'3 × 10⁶ m/s',c:'3 × 10¹⁰ m/s',d:'3 × 10⁴ m/s'},
  {q:'Which element has the chemical symbol Na?',a:'Sodium',b:'Nitrogen',c:'Nickel',d:'Neon'},
  {q:'The process of converting solid directly to gas is called?',a:'Sublimation',b:'Evaporation',c:'Condensation',d:'Distillation'},
  {q:'Which is the hardest natural substance?',a:'Diamond',b:'Quartz',c:'Topaz',d:'Ruby'},
  {q:'Light travels fastest in which medium?',a:'Vacuum',b:'Water',c:'Glass',d:'Air'},
  // ── ART, CULTURE & ARCHITECTURE ──
  {q:'Bharatanatyam is a classical dance form of which state?',a:'Tamil Nadu',b:'Kerala',c:'Andhra Pradesh',d:'Karnataka'},
  {q:'Kathakali is a traditional dance form of which state?',a:'Kerala',b:'Tamil Nadu',c:'Odisha',d:'West Bengal'},
  {q:'The Konark Sun Temple is located in which state?',a:'Odisha',b:'Madhya Pradesh',c:'Rajasthan',d:'Gujarat'},
  {q:'Who composed the Indian National Song "Vande Mataram"?',a:'Bankim Chandra Chatterjee',b:'Rabindranath Tagore',c:'Sarojini Naidu',d:'Muhammad Iqbal'},
  {q:'Who wrote the Indian national anthem "Jana Gana Mana"?',a:'Rabindranath Tagore',b:'Bankim Chandra Chatterjee',c:'Sarojini Naidu',d:'Subhas Chandra Bose'},
  {q:'The Khajuraho temples are located in which state?',a:'Madhya Pradesh',b:'Rajasthan',c:'Uttar Pradesh',d:'Maharashtra'},
  {q:'Which classical dance form originated in Manipur?',a:'Manipuri',b:'Kathak',c:'Odissi',d:'Mohiniyattam'},
  {q:'The Brihadeeswarar Temple is located in which city?',a:'Thanjavur',b:'Madurai',c:'Kanchipuram',d:'Mamallapuram'},
  {q:'The Hampi ruins belong to which empire?',a:'Vijayanagara',b:'Chola',c:'Maurya',d:'Mughal'},
  {q:'Who is the author of the book "Discovery of India"?',a:'Jawaharlal Nehru',b:'Mahatma Gandhi',c:'Dr. S. Radhakrishnan',d:'Rabindranath Tagore'},
  // ── SPORTS ──
  {q:'The FIFA World Cup is associated with which sport?',a:'Football',b:'Cricket',c:'Hockey',d:'Tennis'},
  {q:'How many players are there in a cricket team?',a:'11',b:'10',c:'12',d:'15'},
  {q:'The Wimbledon Championship is associated with which sport?',a:'Tennis',b:'Cricket',c:'Football',d:'Badminton'},
  {q:'Who is known as the "Flying Sikh" of India?',a:'Milkha Singh',b:'P.T. Usha',c:'Usain Bolt',d:'Hima Das'},
  {q:'The Olympic Games are held every how many years?',a:'4 years',b:'2 years',c:'3 years',d:'5 years'},
  {q:'Which country has won the most FIFA World Cup titles?',a:'Brazil',b:'Germany',c:'Argentina',d:'Italy'},
  {q:'The Ranji Trophy is associated with which sport?',a:'Cricket',b:'Hockey',c:'Football',d:'Badminton'},
  {q:'Who was the first Indian to win an individual Olympic gold medal?',a:'Abhinav Bindra',b:'Neeraj Chopra',c:'Sushil Kumar',d:'Mary Kom'},
  {q:'The Thomas Cup is associated with which sport?',a:'Badminton',b:'Table Tennis',c:'Tennis',d:'Squash'},
  {q:'How many players are in a volleyball team on court?',a:'6',b:'5',c:'7',d:'11'},
  {q:'The Ashes series is played between which two countries?',a:'England and Australia',b:'India and Pakistan',c:'England and India',d:'Australia and South Africa'},
  {q:'In which year were the first modern Olympic Games held?',a:'1896',b:'1900',c:'1888',d:'1920'},
  // ── AWARDS & HONOURS ──
  {q:'The Bharat Ratna is the highest civilian award of which country?',a:'India',b:'Pakistan',c:'Sri Lanka',d:'Nepal'},
  {q:'The Nobel Prize for Peace is awarded in which city?',a:'Oslo',b:'Stockholm',c:'Geneva',d:'London'},
  {q:'Who was the first Indian to receive the Nobel Prize?',a:'Rabindranath Tagore',b:'C.V. Raman',c:'Mother Teresa',d:'Amartya Sen'},
  {q:'The Padma Shri is given in how many categories?',a:'It is a single category award',b:'3 categories',c:'5 categories',d:'2 categories'},
  {q:'The Dronacharya Award is given for excellence in?',a:'Sports coaching',b:'Literature',c:'Science',d:'Social service'},
  {q:'The Arjuna Award is given for outstanding performance in?',a:'Sports',b:'Cinema',c:'Music',d:'Literature'},
  {q:'The Ramon Magsaysay Award is also known as?',a:'Asia\'s Nobel Prize',b:'Pulitzer of Asia',c:'Booker of Asia',d:'Grammy of Asia'},
  {q:'The Man Booker Prize is awarded for?',a:'Fiction writing',b:'Science',c:'Peace',d:'Economics'},
  // ── IMPORTANT DAYS & EVENTS ──
  {q:'World Environment Day is celebrated on which date?',a:'5 June',b:'22 April',c:'21 March',d:'5 December'},
  {q:'Republic Day of India is celebrated on which date?',a:'26 January',b:'15 August',c:'2 October',d:'14 November'},
  {q:'International Women\'s Day is observed on which date?',a:'8 March',b:'14 February',c:'1 May',d:'10 December'},
  {q:'World Health Day is celebrated on which date?',a:'7 April',b:'1 December',c:'24 October',d:'5 June'},
  {q:'Teachers\' Day in India is celebrated on which date?',a:'5 September',b:'14 November',c:'2 October',d:'15 September'},
  {q:'Children\'s Day in India is celebrated on which date?',a:'14 November',b:'5 September',c:'26 January',d:'2 October'},
  {q:'International Yoga Day is observed on which date?',a:'21 June',b:'5 June',c:'22 April',d:'2 October'},
  // ── WORLD GEOGRAPHY ──
  {q:'Which is the largest continent by area?',a:'Asia',b:'Africa',c:'North America',d:'Europe'},
  {q:'The Amazon River flows through which continent?',a:'South America',b:'Africa',c:'Asia',d:'North America'},
  {q:'Which is the smallest country in the world by area?',a:'Vatican City',b:'Monaco',c:'San Marino',d:'Liechtenstein'},
  {q:'The Sahara Desert is located in which continent?',a:'Africa',b:'Asia',c:'Australia',d:'South America'},
  {q:'Which country is known as the Land of the Rising Sun?',a:'Japan',b:'China',c:'South Korea',d:'Thailand'},
  {q:'The Great Barrier Reef is located near which country?',a:'Australia',b:'New Zealand',c:'Indonesia',d:'Philippines'},
  {q:'Which is the longest river in the world?',a:'Nile',b:'Amazon',c:'Yangtze',d:'Mississippi'},
  {q:'The capital of Australia is?',a:'Canberra',b:'Sydney',c:'Melbourne',d:'Perth'},
  {q:'Which continent is known as the Dark Continent?',a:'Africa',b:'Asia',c:'South America',d:'Antarctica'},
  {q:'The Panama Canal connects which two oceans?',a:'Atlantic and Pacific',b:'Indian and Pacific',c:'Atlantic and Indian',d:'Arctic and Pacific'},
  {q:'The largest ocean in the world is?',a:'Pacific Ocean',b:'Atlantic Ocean',c:'Indian Ocean',d:'Arctic Ocean'},
  {q:'Mount Kilimanjaro is located in which country?',a:'Tanzania',b:'Kenya',c:'South Africa',d:'Ethiopia'},
  {q:'Which country has the largest population in the world?',a:'India',b:'China',c:'USA',d:'Indonesia'},
  {q:'The Bermuda Triangle is located in which ocean?',a:'Atlantic Ocean',b:'Pacific Ocean',c:'Indian Ocean',d:'Arctic Ocean'},
  // ── INDIAN CONSTITUTION & GOVERNANCE ──
  {q:'Who is the first citizen of India?',a:'President',b:'Prime Minister',c:'Chief Justice',d:'Vice President'},
  {q:'The Indian Parliament consists of how many houses?',a:'2',b:'3',c:'1',d:'4'},
  {q:'Rajya Sabha is also known as?',a:'Council of States',b:'House of the People',c:'Upper Chamber',d:'Legislative Assembly'},
  {q:'The President of India is elected for a term of how many years?',a:'5 years',b:'4 years',c:'6 years',d:'3 years'},
  {q:'Which is the highest court in India?',a:'Supreme Court',b:'High Court',c:'District Court',d:'Sessions Court'},
  {q:'The Election Commission of India was established in which year?',a:'1950',b:'1947',c:'1952',d:'1949'},
  {q:'How many fundamental duties are there in the Indian Constitution?',a:'11',b:'10',c:'12',d:'9'},
  {q:'The First General Elections in India were held in which year?',a:'1951-52',b:'1947',c:'1950',d:'1955'},
  {q:'Which Article provides for the Right to Equality?',a:'Article 14',b:'Article 19',c:'Article 21',d:'Article 32'},
  {q:'The Ninth Schedule was added to the Constitution by which amendment?',a:'First Amendment',b:'42nd Amendment',c:'44th Amendment',d:'73rd Amendment'},
  // ── BIOLOGY & HEALTH ──
  {q:'Which organ purifies blood in the human body?',a:'Kidney',b:'Liver',c:'Heart',d:'Lungs'},
  {q:'The largest organ of the human body is?',a:'Skin',b:'Liver',c:'Brain',d:'Heart'},
  {q:'Red blood cells are produced in which part of the body?',a:'Bone marrow',b:'Liver',c:'Spleen',d:'Kidney'},
  {q:'The disease caused by deficiency of Vitamin C is?',a:'Scurvy',b:'Rickets',c:'Beri-beri',d:'Night blindness'},
  {q:'Malaria is caused by which organism?',a:'Plasmodium',b:'Bacteria',c:'Virus',d:'Fungus'},
  {q:'Which part of the brain controls body balance?',a:'Cerebellum',b:'Cerebrum',c:'Medulla',d:'Hypothalamus'},
  {q:'Haemoglobin is present in which blood cells?',a:'Red blood cells',b:'White blood cells',c:'Platelets',d:'Plasma'},
  {q:'The disease typhoid is caused by?',a:'Salmonella typhi',b:'Mycobacterium',c:'Plasmodium',d:'Vibrio cholerae'},
  {q:'Which gland is known as the master gland?',a:'Pituitary gland',b:'Thyroid gland',c:'Adrenal gland',d:'Pineal gland'},
  {q:'The normal human body temperature is?',a:'37°C (98.6°F)',b:'36°C (96.8°F)',c:'38°C (100.4°F)',d:'35°C (95°F)'},
  // ── PHYSICS & CHEMISTRY GK ──
  {q:'The SI unit of force is?',a:'Newton',b:'Joule',c:'Watt',d:'Pascal'},
  {q:'The SI unit of electric current is?',a:'Ampere',b:'Volt',c:'Ohm',d:'Watt'},
  {q:'The chemical formula for common salt is?',a:'NaCl',b:'KCl',c:'NaOH',d:'HCl'},
  {q:'pH value of pure water is?',a:'7',b:'6',c:'8',d:'0'},
  {q:'Which metal is liquid at room temperature?',a:'Mercury',b:'Iron',c:'Aluminium',d:'Copper'},
  {q:'The phenomenon of breaking of white light into seven colours is called?',a:'Dispersion',b:'Refraction',c:'Reflection',d:'Diffraction'},
  {q:'Ohm\'s law relates voltage, current and?',a:'Resistance',b:'Power',c:'Capacitance',d:'Inductance'},
  {q:'The chemical name of baking soda is?',a:'Sodium Bicarbonate',b:'Sodium Carbonate',c:'Calcium Carbonate',d:'Potassium Bicarbonate'},
  {q:'The element with atomic number 1 is?',a:'Hydrogen',b:'Helium',c:'Lithium',d:'Carbon'},
  {q:'Which lens is used to correct myopia (near-sightedness)?',a:'Concave lens',b:'Convex lens',c:'Bifocal lens',d:'Cylindrical lens'},
  // ── COMPUTERS & TECHNOLOGY ──
  {q:'Who is known as the father of computers?',a:'Charles Babbage',b:'Alan Turing',c:'John von Neumann',d:'Bill Gates'},
  {q:'What does CPU stand for?',a:'Central Processing Unit',b:'Central Program Unit',c:'Computer Processing Unit',d:'Central Peripheral Unit'},
  {q:'What does HTML stand for?',a:'HyperText Markup Language',b:'High Tech Modern Language',c:'Hyper Transfer Markup Language',d:'Home Tool Markup Language'},
  {q:'RAM stands for?',a:'Random Access Memory',b:'Read Access Memory',c:'Rapid Access Memory',d:'Random Available Memory'},
  {q:'Which programming language is known as the mother of all languages?',a:'C',b:'Java',c:'Python',d:'FORTRAN'},
  {q:'1 Kilobyte (KB) is equal to how many bytes?',a:'1024 bytes',b:'1000 bytes',c:'512 bytes',d:'2048 bytes'},
  {q:'The full form of URL is?',a:'Uniform Resource Locator',b:'Universal Resource Locator',c:'Unified Resource Link',d:'Universal Record Locator'},
  {q:'Which device converts digital signals to analog signals?',a:'Modem',b:'Router',c:'Switch',d:'Hub'},
  {q:'The brain of a computer is?',a:'CPU',b:'RAM',c:'Hard Disk',d:'Monitor'},
  {q:'Which generation of computers used integrated circuits?',a:'Third generation',b:'First generation',c:'Second generation',d:'Fourth generation'},
  // ── ORGANISATIONS & HEADQUARTERS ──
  {q:'The headquarters of the United Nations is located in?',a:'New York',b:'Geneva',c:'London',d:'Paris'},
  {q:'WHO stands for?',a:'World Health Organization',b:'World Humanitarian Organization',c:'World Heritage Organization',d:'World Habitat Organization'},
  {q:'The headquarters of NATO is located in?',a:'Brussels',b:'Washington D.C.',c:'London',d:'Paris'},
  {q:'UNICEF is related to?',a:'Children\'s welfare',b:'Education',c:'Environment',d:'Trade'},
  {q:'The International Court of Justice is located in?',a:'The Hague',b:'Geneva',c:'New York',d:'London'},
  {q:'The headquarters of the International Monetary Fund (IMF) is in?',a:'Washington D.C.',b:'New York',c:'Geneva',d:'London'},
  {q:'ASEAN stands for?',a:'Association of Southeast Asian Nations',b:'Asian Social and Economic Association of Nations',c:'Association of South-East Asian Neighbours',d:'Allied Southeast Asian Network'},
  {q:'The headquarters of the World Trade Organization (WTO) is in?',a:'Geneva',b:'New York',c:'Brussels',d:'Washington D.C.'},
  // ── ENVIRONMENT & ECOLOGY ──
  {q:'The ozone layer is found in which layer of the atmosphere?',a:'Stratosphere',b:'Troposphere',c:'Mesosphere',d:'Thermosphere'},
  {q:'Which gas is responsible for global warming?',a:'Carbon dioxide',b:'Oxygen',c:'Nitrogen',d:'Hydrogen'},
  {q:'The Kyoto Protocol is related to?',a:'Climate change',b:'Nuclear disarmament',c:'Trade liberalisation',d:'Human rights'},
  {q:'Jim Corbett National Park is located in which state?',a:'Uttarakhand',b:'Madhya Pradesh',c:'Rajasthan',d:'Assam'},
  {q:'The national animal of India is?',a:'Bengal Tiger',b:'Asiatic Lion',c:'Indian Elephant',d:'Indian Rhinoceros'},
  {q:'Which is the national bird of India?',a:'Indian Peacock',b:'Indian Parrot',c:'Flamingo',d:'Indian Eagle'},
  {q:'The national flower of India is?',a:'Lotus',b:'Rose',c:'Jasmine',d:'Sunflower'},
  {q:'CFC gases are responsible for the depletion of which layer?',a:'Ozone layer',b:'Troposphere',c:'Ionosphere',d:'Exosphere'},
  {q:'The Kaziranga National Park is famous for which animal?',a:'One-horned Rhinoceros',b:'Bengal Tiger',c:'Asiatic Lion',d:'Indian Elephant'},
  {q:'Which day is celebrated as Earth Day?',a:'22 April',b:'5 June',c:'21 March',d:'22 March'},
  // ── MISCELLANEOUS GK ──
  {q:'The Statue of Liberty is located in which country?',a:'USA',b:'France',c:'UK',d:'Italy'},
  {q:'Who invented the telephone?',a:'Alexander Graham Bell',b:'Thomas Edison',c:'Nikola Tesla',d:'Guglielmo Marconi'},
  {q:'The currency of the United Kingdom is?',a:'Pound Sterling',b:'Euro',c:'Dollar',d:'Franc'},
  {q:'The Eiffel Tower is located in which city?',a:'Paris',b:'London',c:'Rome',d:'Berlin'},
  {q:'Which country is known as the Land of Thousand Lakes?',a:'Finland',b:'Sweden',c:'Norway',d:'Canada'},
  {q:'The Great Wall is located in which country?',a:'China',b:'Japan',c:'India',d:'Mongolia'},
  {q:'Who painted the Mona Lisa?',a:'Leonardo da Vinci',b:'Michelangelo',c:'Raphael',d:'Pablo Picasso'},
  {q:'The first President of India was?',a:'Dr. Rajendra Prasad',b:'Dr. S. Radhakrishnan',c:'Zakir Husain',d:'V.V. Giri'},
  {q:'Mahatma Gandhi was born in which year?',a:'1869',b:'1870',c:'1867',d:'1872'},
  {q:'Who discovered penicillin?',a:'Alexander Fleming',b:'Louis Pasteur',c:'Edward Jenner',d:'Robert Koch'},
  {q:'The Taj Mahal is located in which city?',a:'Agra',b:'Delhi',c:'Jaipur',d:'Lucknow'},
  {q:'Which country gifted the Statue of Liberty to the United States?',a:'France',b:'UK',c:'Germany',d:'Spain'},
  {q:'The currency of China is?',a:'Renminbi (Yuan)',b:'Yen',c:'Won',d:'Baht'},
  {q:'Who is known as the "Missile Man of India"?',a:'Dr. A.P.J. Abdul Kalam',b:'Vikram Sarabhai',c:'Homi Bhabha',d:'Satish Dhawan'},
  {q:'The Leaning Tower of Pisa is located in which country?',a:'Italy',b:'France',c:'Spain',d:'Greece'},
  {q:'Which planet is known as the Morning Star?',a:'Venus',b:'Mars',c:'Jupiter',d:'Mercury'},
  {q:'The largest bone in the human body is?',a:'Femur',b:'Humerus',c:'Tibia',d:'Spine'},
  {q:'World War II ended in which year?',a:'1945',b:'1944',c:'1946',d:'1943'},
  {q:'The United Nations was established in which year?',a:'1945',b:'1946',c:'1944',d:'1950'},
  {q:'Who wrote the book "My Experiments with Truth"?',a:'Mahatma Gandhi',b:'Jawaharlal Nehru',c:'Rabindranath Tagore',d:'B.R. Ambedkar'},
  // ── ADDITIONAL INDIAN HISTORY ──
  {q:'The Doctrine of Lapse was introduced by which Governor-General?',a:'Lord Dalhousie',b:'Lord Wellesley',c:'Lord Canning',d:'Lord Bentinck'},
  {q:'Who founded the Brahmo Samaj?',a:'Raja Ram Mohan Roy',b:'Swami Vivekananda',c:'Dayanand Saraswati',d:'Ishwar Chandra Vidyasagar'},
  {q:'The Lucknow Pact of 1916 was an agreement between?',a:'Congress and Muslim League',b:'Congress and British',c:'Muslim League and British',d:'Congress and Hindu Mahasabha'},
  {q:'Who started the Self-Respect Movement?',a:'E.V. Ramasamy Periyar',b:'B.R. Ambedkar',c:'Jyotirao Phule',d:'Mahatma Gandhi'},
  {q:'The Champaran Satyagraha of 1917 was related to?',a:'Indigo cultivation',b:'Salt tax',c:'Land tax',d:'Cotton farming'},
  {q:'Who was the first Indian to become a member of the British Parliament?',a:'Dadabhai Naoroji',b:'W.C. Bannerjee',c:'Gopal Krishna Gokhale',d:'Pherozeshah Mehta'},
  {q:'The Cripps Mission visited India in which year?',a:'1942',b:'1940',c:'1946',d:'1943'},
  {q:'The Indian Independence Act was passed in which year?',a:'1947',b:'1946',c:'1945',d:'1950'},
  {q:'Who presided over the first session of the Indian National Congress?',a:'W.C. Bannerjee',b:'A.O. Hume',c:'Dadabhai Naoroji',d:'Surendranath Banerjee'},
  {q:'The Swadeshi Movement was started in response to?',a:'Partition of Bengal',b:'Rowlatt Act',c:'Jallianwala Bagh',d:'Simon Commission'},
  // ── MORE GEOGRAPHY ──
  {q:'The Tropic of Cancer passes through how many Indian states?',a:'8',b:'6',c:'7',d:'9'},
  {q:'Which river originates from the Amarkantak Plateau?',a:'Narmada',b:'Tapti',c:'Godavari',d:'Mahanadi'},
  {q:'Loktak Lake is located in which state?',a:'Manipur',b:'Meghalaya',c:'Assam',d:'Tripura'},
  {q:'The highest waterfall in India is?',a:'Jog Falls',b:'Dudhsagar Falls',c:'Kunchikal Falls',d:'Athirappilly Falls'},
  {q:'The Brahmaputra River originates from?',a:'Angsi Glacier in Tibet',b:'Gangotri Glacier',c:'Yamunotri',d:'Siachen Glacier'},
  {q:'Which Indian state is the largest by area?',a:'Rajasthan',b:'Madhya Pradesh',c:'Maharashtra',d:'Uttar Pradesh'},
  {q:'The Nilgiri Hills are located in which state?',a:'Tamil Nadu',b:'Kerala',c:'Karnataka',d:'Andhra Pradesh'},
  {q:'India\'s longest national highway is?',a:'NH 44',b:'NH 7',c:'NH 1',d:'NH 48'},
  {q:'The soil found in the Deccan Plateau is primarily?',a:'Black soil (Regur)',b:'Red soil',c:'Alluvial soil',d:'Laterite soil'},
  {q:'Which is the highest peak in the Satpura Range?',a:'Dhupgarh',b:'Pachmarhi',c:'Mahendragiri',d:'Anamudi'},
  // ── MORE ECONOMICS ──
  {q:'Which bank has the tagline "The Name You Can Bank Upon"?',a:'Canara Bank',b:'SBI',c:'PNB',d:'BOB'},
  {q:'Inflation means?',a:'Rise in general price level',b:'Fall in general price level',c:'Constant price level',d:'Rise in production'},
  {q:'The concept of "Mixed Economy" means?',a:'Co-existence of public and private sectors',b:'Only public sector',c:'Only private sector',d:'Foreign companies only'},
  {q:'The term "Budget" is derived from which language?',a:'French',b:'Latin',c:'Greek',d:'German'},
  {q:'Census in India is conducted after every how many years?',a:'10 years',b:'5 years',c:'15 years',d:'20 years'},
  {q:'Which sector contributes the most to India\'s GDP?',a:'Service sector',b:'Agriculture',c:'Manufacturing',d:'Mining'},
  {q:'Repo Rate is the rate at which?',a:'RBI lends to commercial banks',b:'Banks lend to customers',c:'RBI borrows from banks',d:'Banks borrow from each other'},
  {q:'MUDRA Bank was launched in which year?',a:'2015',b:'2014',c:'2016',d:'2017'},
  {q:'What does EPF stand for?',a:'Employees\' Provident Fund',b:'Emergency Public Fund',c:'Employer Payment Fund',d:'Economic Planning Fund'},
  {q:'The term "Demographic Dividend" refers to?',a:'A large working-age population relative to dependents',b:'High birth rate',c:'Low death rate',d:'High immigration'},
  // ── MORE SCIENCE GK ──
  {q:'Which acid is present in lemon?',a:'Citric acid',b:'Acetic acid',c:'Tartaric acid',d:'Formic acid'},
  {q:'The metal used in making filament of electric bulb is?',a:'Tungsten',b:'Copper',c:'Aluminium',d:'Iron'},
  {q:'Photosynthesis takes place in which part of the plant?',a:'Leaves',b:'Roots',c:'Stem',d:'Flowers'},
  {q:'Which gas is filled in electric bulbs?',a:'Argon',b:'Nitrogen',c:'Hydrogen',d:'Oxygen'},
  {q:'Sound cannot travel through?',a:'Vacuum',b:'Water',c:'Air',d:'Steel'},
  {q:'The study of earthquakes is called?',a:'Seismology',b:'Geology',c:'Meteorology',d:'Volcanology'},
  {q:'The lightest gas in the universe is?',a:'Hydrogen',b:'Helium',c:'Nitrogen',d:'Oxygen'},
  {q:'Rust is chemically known as?',a:'Iron oxide',b:'Iron carbonate',c:'Iron sulphate',d:'Iron chloride'},
  {q:'Which vitamin deficiency causes night blindness?',a:'Vitamin A',b:'Vitamin B',c:'Vitamin C',d:'Vitamin D'},
  {q:'The colour of pure water is?',a:'Colourless',b:'Blue',c:'White',d:'Light green'},
  // ── FIRSTS IN INDIA ──
  {q:'Who was the first Prime Minister of India?',a:'Jawaharlal Nehru',b:'Sardar Patel',c:'Dr. Rajendra Prasad',d:'Lal Bahadur Shastri'},
  {q:'Who was the first Indian woman in space?',a:'Kalpana Chawla',b:'Sunita Williams',c:'Tessy Thomas',d:'Ritu Karidhal'},
  {q:'The first Indian satellite launched was?',a:'Aryabhata',b:'Bhaskara',c:'INSAT-1A',d:'Rohini'},
  {q:'India\'s first nuclear test was conducted in which year?',a:'1974',b:'1971',c:'1998',d:'1962'},
  {q:'Who was the first woman Chief Minister of an Indian state?',a:'Sucheta Kriplani',b:'Indira Gandhi',c:'Jayalalithaa',d:'Mamata Banerjee'},
  {q:'The first railway line in India was between?',a:'Mumbai and Thane',b:'Delhi and Agra',c:'Kolkata and Delhi',d:'Chennai and Bangalore'},
  {q:'Who was the first Indian to receive the Bharat Ratna?',a:'Dr. Sarvepalli Radhakrishnan',b:'C. Rajagopalachari',c:'C.V. Raman',d:'Jawaharlal Nehru'},
  {q:'India\'s first IIT was established in which city?',a:'Kharagpur',b:'Mumbai',c:'Delhi',d:'Chennai'},
  {q:'Who was the first woman judge of the Supreme Court of India?',a:'Justice M. Fathima Beevi',b:'Justice Sujata Manohar',c:'Justice Ruma Pal',d:'Justice Indu Malhotra'},
  {q:'The first metro rail in India started in which city?',a:'Kolkata',b:'Delhi',c:'Mumbai',d:'Chennai'},
  // ── BOOKS & AUTHORS ──
  {q:'Who wrote "Wings of Fire"?',a:'Dr. A.P.J. Abdul Kalam',b:'Jawaharlal Nehru',c:'Mahatma Gandhi',d:'Vikram Seth'},
  {q:'The author of "Gitanjali" is?',a:'Rabindranath Tagore',b:'Sarojini Naidu',c:'Bankim Chandra',d:'Premchand'},
  {q:'Who wrote "Arthashastra"?',a:'Chanakya (Kautilya)',b:'Kalidasa',c:'Valmiki',d:'Tulsidas'},
  {q:'The book "Mein Kampf" was written by?',a:'Adolf Hitler',b:'Winston Churchill',c:'Joseph Stalin',d:'Benito Mussolini'},
  {q:'"A Brief History of Time" is written by?',a:'Stephen Hawking',b:'Albert Einstein',c:'Isaac Newton',d:'Carl Sagan'},
  {q:'Who is the author of "Ramayana"?',a:'Valmiki',b:'Vyasa',c:'Tulsidas',d:'Kalidasa'},
  {q:'"The God of Small Things" is written by?',a:'Arundhati Roy',b:'Jhumpa Lahiri',c:'Salman Rushdie',d:'Amitav Ghosh'},
  // ── INVENTIONS & DISCOVERIES ──
  {q:'Who invented the printing press?',a:'Johannes Gutenberg',b:'Alexander Graham Bell',c:'Thomas Edison',d:'Benjamin Franklin'},
  {q:'The theory of relativity was proposed by?',a:'Albert Einstein',b:'Isaac Newton',c:'Galileo Galilei',d:'Niels Bohr'},
  {q:'Who discovered gravity?',a:'Isaac Newton',b:'Galileo Galilei',c:'Albert Einstein',d:'Stephen Hawking'},
  {q:'The electric bulb was invented by?',a:'Thomas Edison',b:'Benjamin Franklin',c:'Michael Faraday',d:'Nikola Tesla'},
  {q:'Who invented the World Wide Web?',a:'Tim Berners-Lee',b:'Vint Cerf',c:'Bill Gates',d:'Steve Jobs'},
  {q:'X-rays were discovered by?',a:'Wilhelm Roentgen',b:'Marie Curie',c:'Alexander Fleming',d:'Louis Pasteur'},
  {q:'The steam engine was improved by?',a:'James Watt',b:'Thomas Newcomen',c:'George Stephenson',d:'Robert Fulton'},
  // ── ADDITIONAL POLITY ──
  {q:'Money bills can be introduced in which house of Parliament?',a:'Lok Sabha',b:'Rajya Sabha',c:'Both houses',d:'State Legislature'},
  {q:'The Attorney General of India is appointed by whom?',a:'President',b:'Prime Minister',c:'Chief Justice',d:'Parliament'},
  {q:'The Inter-State Council is chaired by?',a:'Prime Minister',b:'President',c:'Home Minister',d:'Speaker of Lok Sabha'},
  {q:'The National Emergency under Article 352 was first proclaimed in which year?',a:'1962',b:'1971',c:'1975',d:'1965'},
  {q:'The Anti-Defection Law was added by which amendment?',a:'52nd Amendment',b:'42nd Amendment',c:'44th Amendment',d:'61st Amendment'},
  {q:'CAG stands for?',a:'Comptroller and Auditor General',b:'Controller and Auditor General',c:'Chief Audit General',d:'Central Audit Group'},
  {q:'The Finance Commission is constituted every?',a:'5 years',b:'3 years',c:'10 years',d:'4 years'},
  {q:'Article 21 of the Indian Constitution deals with?',a:'Right to Life and Personal Liberty',b:'Right to Equality',c:'Right to Freedom of Religion',d:'Right against Exploitation'},
  // ── ADDITIONAL GEOGRAPHY ──
  {q:'Which Indian state has the highest literacy rate?',a:'Kerala',b:'Goa',c:'Mizoram',d:'Tripura'},
  {q:'The Siachen Glacier is located in which mountain range?',a:'Karakoram',b:'Himalayas',c:'Hindu Kush',d:'Aravalli'},
  {q:'Which river forms the boundary between India and Bangladesh?',a:'Meghna',b:'Ganga',c:'Brahmaputra',d:'Teesta'},
  {q:'The largest producer of tea in India is?',a:'Assam',b:'West Bengal',c:'Kerala',d:'Tamil Nadu'},
  {q:'Bhakra Nangal Dam is built on which river?',a:'Sutlej',b:'Beas',c:'Ravi',d:'Chenab'},
  {q:'Which state is the largest producer of rice in India?',a:'West Bengal',b:'Punjab',c:'Uttar Pradesh',d:'Andhra Pradesh'},
  {q:'The Godavari River originates from?',a:'Trimbakeshwar, Nashik',b:'Mahabaleshwar',c:'Western Ghats, Kerala',d:'Amarkantak'},
  {q:'The Rann of Kutch is located in which state?',a:'Gujarat',b:'Rajasthan',c:'Haryana',d:'Maharashtra'},
  // ── ADDITIONAL MISCELLANEOUS ──
  {q:'The Olympic symbol has how many rings?',a:'5',b:'4',c:'6',d:'7'},
  {q:'Which gas is commonly used in refrigerators?',a:'Freon',b:'Ammonia',c:'Carbon dioxide',d:'Nitrogen'},
  {q:'The instrument used to measure atmospheric pressure is?',a:'Barometer',b:'Thermometer',c:'Hygrometer',d:'Anemometer'},
  {q:'What does UNESCO stand for?',a:'United Nations Educational, Scientific and Cultural Organization',b:'United Nations Economic and Social Council Organization',c:'United Nations Environmental and Scientific Council Organization',d:'Universal Nations Education, Science and Culture Organization'},
  {q:'The chemical name of Plaster of Paris is?',a:'Calcium Sulphate Hemihydrate',b:'Calcium Carbonate',c:'Sodium Bicarbonate',d:'Calcium Chloride'},
  {q:'Radio waves were first discovered by?',a:'Heinrich Hertz',b:'Guglielmo Marconi',c:'Nikola Tesla',d:'James Maxwell'},
  {q:'The vitamin necessary for blood clotting is?',a:'Vitamin K',b:'Vitamin C',c:'Vitamin A',d:'Vitamin E'},
  {q:'The study of fungi is called?',a:'Mycology',b:'Virology',c:'Bacteriology',d:'Botany'},
  {q:'Which acid is present in vinegar?',a:'Acetic acid',b:'Citric acid',c:'Hydrochloric acid',d:'Sulphuric acid'},
  {q:'The instrument used to measure humidity is?',a:'Hygrometer',b:'Barometer',c:'Thermometer',d:'Anemometer'},
  {q:'Who is known as the "Father of the Nation"?',a:'Mahatma Gandhi',b:'Jawaharlal Nehru',c:'Sardar Patel',d:'Subhas Chandra Bose'},
  {q:'The study of weather is called?',a:'Meteorology',b:'Climatology',c:'Geology',d:'Astronomy'},
  {q:'Which Indian state is known as the "Spice Garden of India"?',a:'Kerala',b:'Karnataka',c:'Tamil Nadu',d:'Andhra Pradesh'},
  {q:'The Tropic of Cancer passes through which Indian city?',a:'Kolkata',b:'Mumbai',c:'Delhi',d:'Chennai'},
  {q:'What is the approximate age of Earth?',a:'4.5 billion years',b:'3.5 billion years',c:'5.5 billion years',d:'2.5 billion years'},
  {q:'Which planet has the Great Red Spot?',a:'Jupiter',b:'Mars',c:'Saturn',d:'Neptune'},
  {q:'The chemical formula for methane is?',a:'CH₄',b:'CO₂',c:'C₂H₆',d:'C₃H₈'},
  {q:'Who was the first man to walk on the moon?',a:'Neil Armstrong',b:'Buzz Aldrin',c:'Yuri Gagarin',d:'Michael Collins'},
  {q:'The Universal Declaration of Human Rights was adopted in which year?',a:'1948',b:'1945',c:'1950',d:'1947'},
  {q:'Which country has the most time zones?',a:'France',b:'Russia',c:'USA',d:'China'},
  {q:'The largest desert in the world is?',a:'Sahara Desert',b:'Gobi Desert',c:'Arabian Desert',d:'Kalahari Desert'},
  {q:'Who is known as the "Father of Genetics"?',a:'Gregor Mendel',b:'Charles Darwin',c:'Louis Pasteur',d:'Watson and Crick'},
  {q:'The lightest metal known is?',a:'Lithium',b:'Aluminium',c:'Sodium',d:'Magnesium'},
  {q:'Which planet is known as the "Evening Star"?',a:'Venus',b:'Mars',c:'Jupiter',d:'Saturn'},
  {q:'The state with the highest forest cover in India is?',a:'Madhya Pradesh',b:'Arunachal Pradesh',c:'Chhattisgarh',d:'Maharashtra'},
  {q:'White revolution in India is associated with?',a:'Milk production',b:'Wheat production',c:'Rice production',d:'Fish production'},
  {q:'Green revolution in India is associated with?',a:'Food grain production',b:'Milk production',c:'Fish production',d:'Tea production'},
  {q:'Blue revolution in India is associated with?',a:'Fish production',b:'Milk production',c:'Food grain production',d:'Oil production'},
  {q:'Which Indian city is known as the "City of Nawabs"?',a:'Lucknow',b:'Hyderabad',c:'Bhopal',d:'Delhi'},
  {q:'The first newspaper in India was?',a:'Bengal Gazette',b:'The Hindu',c:'Times of India',d:'Dainik Jagran'},
  {q:'The Bermuda Triangle is also known as?',a:'Devil\'s Triangle',b:'Death Triangle',c:'Mystery Triangle',d:'Atlantic Triangle'},
  {q:'Which Indian state was formed on 2 June 2014?',a:'Telangana',b:'Jharkhand',c:'Chhattisgarh',d:'Uttarakhand'},
  {q:'The Kumbh Mela is held at how many places?',a:'4',b:'3',c:'5',d:'2'},
  {q:'Which is the tallest statue in the world?',a:'Statue of Unity',b:'Statue of Liberty',c:'Spring Temple Buddha',d:'Christ the Redeemer'},
  {q:'Indian Space Research Organisation (ISRO) was established in which year?',a:'1969',b:'1972',c:'1975',d:'1962'},
  {q:'The Chandrayaan-1 mission was launched in which year?',a:'2008',b:'2013',c:'2010',d:'2019'},
  {q:'Which is the oldest mountain range in India?',a:'Aravalli Range',b:'Vindhya Range',c:'Western Ghats',d:'Eastern Ghats'},
  {q:'India became a republic on which date?',a:'26 January 1950',b:'15 August 1947',c:'26 November 1949',d:'2 October 1950'},
  {q:'The Panchayati Raj system operates at how many levels?',a:'3 levels',b:'2 levels',c:'4 levels',d:'5 levels'},
  {q:'Which river is called the "Ganga of the South"?',a:'Godavari',b:'Krishna',c:'Cauvery',d:'Tungabhadra'},
  {q:'The largest gland in the human body is?',a:'Liver',b:'Pancreas',c:'Thyroid',d:'Pituitary'},
  {q:'The first woman to climb Mount Everest was?',a:'Junko Tabei',b:'Bachendri Pal',c:'Santosh Yadav',d:'Arunima Sinha'},
  {q:'The first Indian woman to climb Mount Everest?',a:'Bachendri Pal',b:'Santosh Yadav',c:'Arunima Sinha',d:'Malavath Poorna'},
];
